### ISSUE TITLE
./fasmg: cannot execute binary file

### ISSUE THREAD

**Issue by salusijf** [lantonov/asmFish#101]
Hello,

I try to compile asmFish on MacOS X and I have the following error : 

./fasmg: cannot execute binary file

Could you help me please ?

**Comment by MichaelB7** [comment]
It’s either a permission issue or you are trying to run the Linux version.  In terminal , where you have fasmg, try this . Type “chmod 755 fasmg”.   If that doesn’t work, make sure you obtained the correct fasmg binary for macOS.

**Comment by salusijf** [comment]
Thanks.
