### ISSUE TITLE
asmFish_2018-02-02 crashing

### ISSUE THREAD

**Issue by syzygy1** [lantonov/asmFish#104]
Both asmFishL_2018-02-02_base and asmFishL_2018-02-02_popcnt segfault immediately on my PC (which is too old to try _bmi2).

Same for asmfish created with "make asmquick".

**Comment by lantonov** [comment]
You are right, unfortunately. I am on Windows 10 and all Windows binaries work well. However, on Bash on Ubuntu on Windows, all Linux binaries (including the bmi2 one) give the error: Exec format error. Older Linux binaries work normally. I am reverting it.
Windows executables will remain in case someone wants to use a large book.

**Comment by asmfishcc** [comment]
Given the performance of Stockfish 9, Asmfish is currently obsolete. I hope it will soon be updated with the latest patches...

**Comment by Nordlandia** [comment]
Many requests Asmfish 9. In the meantime Cfish 9 works well.

**Comment by pachnes** [comment]
macOS asmfish for modern x64 cpus is not recognized as a valid macOS executable file.

**Comment by lantonov** [comment]
@pachnes 
It is to be expected if it's asmFishX_2018-02-02 as Linux ones don't work too. I will scrap these. If benches correspond, I will soon (several hours) update the code with at least one consecutive patch [Capture Stat Simplification- Bench: 5363761](https://github.com/official-stockfish/Stockfish/commit/87452f3a8c913cb795f04db132ff0f56ee471a62) from Nov 10 SF

**Comment by pachnes** [comment]
thx

**Comment by lantonov** [comment]
Sorry, benches differ and can't make them the same.
