### ISSUE TITLE
Uci Parametres

### ISSUE THREAD

**Issue by cosmic4444** [lantonov/asmFish#11]
Hallo, lantonov, could you create such parameter for asmFish as to add bin book, because of abscence of it, asmfish is always losing, you can learn more about this problem from my tests here: http://immortalchess.net/forum/showpost.php?p=738525&postcount=2366 and http://immortalchess.net/forum/showpost.php?p=739125&postcount=2372 and http://immortalchess.net/forum/showpost.php?p=739125&postcount=2372 and http://immortalchess.net/forum/showpost.php?p=739413&postcount=2376 
Thank you

**Comment by lantonov** [comment]
Because asmFish always runs in a GUI, you can use a GUI that loads a bin book such as Winboard / Xboard, Scid, etc. This is what I do when I enter officially as a computer in the online chess sites. asmFish with a strong GUI bin book is an absolute computer killer there.
As concerns immortalchess, I cannot enter because I have no account for that site.

**Comment by cosmic4444** [comment]
asmFish has won all the tests, that I held, I suppose this is the strongest chess engine in the world right now, but it always loses to brainfish with cerebellum bin book as you can see http://s019.radikal.ru/i604/1612/ea/55813c90272b.jpg 
http://s017.radikal.ru/i409/1612/37/2a1eebf93aa1.jpg
http://s018.radikal.ru/i525/1612/36/7e349e61cf2e.jpg

Brainfish have such a parameter http://s018.radikal.ru/i520/1612/2a/c074a2d0d152.jpg
while asmFish don't have http://s019.radikal.ru/i625/1612/6d/a8418508b365.jpg

If you can add it, there will be no equal engine in the world, and asmFish would be unbeatable, I'm trully believe in that. Thank you

**Comment by lantonov** [comment]
![image](https://cloud.githubusercontent.com/assets/6498222/21401095/e5c8f8f8-c7aa-11e6-9a17-2c33768a616c.png)

This is asmFish with loaded Cerebellum book. 
Actually, there is a function in the present asmFish to prepare Cerebellum book to be used by asmFish. For more details see the Readme file in https://github.com/lantonov/asmFish/tree/executables/Cerebellum

**Comment by cosmic4444** [comment]
I always used popcnt versions) Thanks a lot for your explanations and work) I'll continue testing

**Comment by lantonov** [comment]
You can use Cerebellum in all flavors of asmFish and pedantFish (base, popcnt, and bmi2). Good luck!

**Comment by cosmic4444** [comment]
Sorry for my stupidness, but I can't understand what exatctly I should do after 5 step, I've created new file pedantFish_popcnt.exe, but what next, could you help please and explain with more simple words)

http://s011.radikal.ru/i318/1612/09/8085c7dd4eeb.jpg
