### ISSUE TITLE
SlowMover not working

### ISSUE THREAD

**Issue by lantonov** [lantonov/asmFish#117]
The issue speaks for itself
![image](https://user-images.githubusercontent.com/6498222/36505682-2d3c178c-174c-11e8-944b-b9cbe77405b8.png)
My suspicion is in this piece of code in Uci.asm:691
```assembly
	    lea  rcx, [sz_slowmover]
	    lea  rbx, [.SlowMover]
```
Will try to substitute this with
```assembly
		lea   rcx, [sz_slowmover]
	       call   CmpStringCaseless
		lea   rbx, [.SlowMover]
	       test   eax, eax
		jnz   .CheckValue
```
Entering the options reacts normal
![image](https://user-images.githubusercontent.com/6498222/36506797-86529a5a-174f-11e8-8766-10d0f746645e.png)
Have to think of a test to check if it's working

**Comment by lantonov** [comment]
60 + 0 sec games with asmFish (SlowMover=10) vs asmFish (SlowMover=1000)
1 game draw time 49 vs 1.2 sec
2 game draw time 47 vs 0.9 sec
3 game draw time 45 vs 0.8 sec
4 game White mates time 43 vs 0.2 sec
5 game draw time 43 vs 0.8 sec

**Comment by CounterPly** [comment]
I apologize for all of these bugs that apparently slipped through in my original OTM patch. Looking back at the problems that have surfaced recently, I realize that this was somewhat sloppy work on my part.

I appreciate all of the troubleshooting that you have been doing, Lyudmil. I am in the midst of a few non-chess related deadlines at the moment, but I should be able to help you with these tests + corrections by this weekend (if they are still necessary).

**Comment by lantonov** [comment]
Hi Justin,
Please do not mind it at all. The aim to working in a team is to look the code over and find errors or things that can be improved. I appreciate your submission of patches that are difficult for me to do as I am a complete beginner in assembly. Your help is all the more valuable as Moha, the assembly guru, is busy with other projects. Please keep on doing your good work.
