### ISSUE TITLE
Directory for old executables

### ISSUE THREAD

**Issue by pachnes** [lantonov/asmFish#118]
Hi Lantonov,

could you please make directories in "linux", "windows", "osx", "arm", "matefinder" and move the old executables there? this would be very nice. :)

Kind regards, Thomas

**Comment by lantonov** [comment]
I agree that this will be more user-friendly as users don't have to scroll and search a large list of old programs. It would mean some additional work because moving files between directories in Git / GitHub is not very trivial.

**Comment by lantonov** [comment]
The new executables are in the respective folders in master branch and the old executables are in the 'executables' branch as before

**Comment by pachnes** [comment]
thx :)
