### ISSUE TITLE
What is TTFILE? 

### ISSUE THREAD

**Issue by Marihuanero** [lantonov/asmFish#122]
What's TTfile and how can i use it.? Does it make the engine stronger?

**Comment by CounterPly** [comment]
It is equivalent to the "save hash" feature found in many other engines (TT stands for Transposition Table). It is primarily used for deep analysis of chess positions when the user would like to "save" an analysis and return to it at a later time. It is not helpful for engine-vs-engine matches, and it doesn't really make the engine "stronger." It is just a feature for the convenience of the user (correspondence players typically make the most use of this feature).

To use this feature simply designate the location of the file (.hsh extension works fine) and then when you want to return to the position later you can load up your saved file and immediately restart analyzing where you last left off. 

Refer to the Mark-Down documentation on the front page of this repository for more details.

**Comment by Marihuanero** [comment]
@counterply. Thnks for the quick reply.

**Comment by TasicV** [comment]
Hi,
I read this, but i dont know who make first this TTFILE ? Is that txt file with extension .HSH ? Can I create this file, then give in parameter path of this file? I make path in parameter, but engine not create TTFILE in folder where is path of parameter! Can you explain about this?
Thanks

**Comment by CounterPly** [comment]
Resolved at #174 for anyone else with this question.

**Comment by TasicV** [comment]
How to see what is inside of this file? Maybe I have two same file, and I forgot variant inside... Notepad can not see inside. Any sugestion? Sorry and thanks!!!

**Comment by TasicV** [comment]
Also (sorry) question how to change size of TTFILE from 4GB to 32GB?

**Comment by double-beep** [comment]
To change the size of TTFILE you need to increase or decrease the hash. What chess GUI do you use?

> How to see what is inside of this file? Maybe I have two same file, and I forgot variant inside... Notepad can not see inside. Any sugestion? Sorry and thanks!!!

I use EmEditor. It can see inside all files.

**Comment by double-beep** [comment]
Please your questions, e.t.c. now to #174.

**Comment by TasicV** [comment]
I use Fritz, Aquarium... And I use 4Gb hash. I have 16 Gb RAM memory. Is that good or bad?
Thanks

**Comment by double-beep** [comment]
Please think that my computer has only 4GB RAM! But why don't you use more for quick and deeper analysis (e.g. 8GB+)? Threads will help also. How many do you have?

**Comment by TasicV** [comment]
I use Ryzen 7 1700, with 8 CPU / 16 treads, 16 GB RAM memory, on Fritz or Aquarium. Also I must ask, what is better for this AMD processor, BMI2 or POPCNT engine? How to bench engins and what I looking in bench test, what is better (K/s or nodes/s or time) ?

**Comment by double-beep** [comment]
This is so modern! Why don't you use more hash? How many threads do you use for analysis? and Do you use your computer only for chess?

**Comment by TasicV** [comment]
I use 15 treads from last time and 4GB of hash. I use this comp for CORR games, and I looking good engine for this. If I use more then 4GB hash, engine crashing/stop working. Work, work and then just stop working, like no anymore memory for engine.
I dont know how to find good engine and parameters for this good processor... I testing some engins in my games, and I find many wrong evaluation. Some where is egal position, engine say +0.70 (like RAUBFISH), some where engine not see 2 or 3 moves forward, where evaluation is +0.80, and engine say =0.00.

**Comment by double-beep** [comment]
It's easy to bench an engine. Open the exe file directly and press bench. You can customize also the hash, threads and depth. Default is 16(hash) 1(threads) 13(depth). The bench number is the `Nodes Searched`. But when you see bench: ********* just remember this is after 16MB of hash, 1 thread and depth 13. What do you use, popcnt or bmi2?
1. BMI2 (haswell CPU's)-best
2. POPCNT (modern computers)
3. BASE (x64)

I think you should use bmi2 but for sure @Counterply should answer.

**Comment by TasicV** [comment]
I compare 4 engines on Ryzen 7 1700 with 16Gb RAM memory. This is my file of bench 4 AsmFish engines.
![bench asmfish on ryzen 7 - 1700](https://user-images.githubusercontent.com/19522125/41979980-a61aeea8-7a25-11e8-85a5-2d73e71193da.jpg)

After this, I see engine * asmFishW_2018-06-25_popcnt * is the best for this comp. Am I right?

**Comment by Ipmanchess** [comment]
Yes you are right..for AMD is pop version better!
If you want to see a bench list here's my link: http://www.ipmanchess.yolasite.com/amd---intel-chess-bench.php

**Comment by double-beep** [comment]
I think that you should add to comparison these two benches from AppVeyor console.
![console](https://user-images.githubusercontent.com/38133098/41981525-ca0e000a-7a31-11e8-929a-adc9baf14367.png)

**Comment by CounterPly** [comment]
@double-beep Good idea. I will look into it after work, thanks.

**Comment by TasicV** [comment]
Yes, bether engine then last from 26.06.2018. But for AMD Ryzen 7 bether is version POPCNT!
![asmfish 2018-06-27](https://user-images.githubusercontent.com/19522125/41990277-3b778f26-7a42-11e8-98d5-2f8b283c86d6.jpg)
