### ISSUE TITLE
Correct Setting for asmfishW

### ISSUE THREAD

**Issue by Marihuanero** [lantonov/asmFish#123]
I have another question.
What should be the correct setting for "slowmover", moveoverhead, MinThinkTime?
The Specs of my PC:
Processor i7, 12 GB RAM, SSD, WINDOWS 10.
Thank you so much for this place where i can clarify my doubts.

**Comment by lantonov** [comment]
If you have no problem with time management, leave them at the defaults:
SlowMover 89
MoveOverhead 30
MinThinkTime 20
