### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by sohel1214** [lantonov/asmFish#133]
engine output show no large pages ? how  get large pages? pls help

**Comment by sohel1214** [comment]
# @

**Comment by sohel1214** [comment]
i check houdini then engine output show 128 MB large pages hash but when check asmfish engine output show no large pages..............pls help

**Comment by lantonov** [comment]
You should activate the option Large Pages by some checkbox in your GUI. 
In the engine CLI large pages is activated with
`setoption name LargePages value true`
The default is 'false'

**Comment by sohel1214** [comment]
thanks for reply . if possible large pages value  default 'true'

**Comment by lantonov** [comment]
Large pages fragment the computer memory and it becomes slower. That's why most users avoid them and the default is 'false'

**Comment by sohel1214** [comment]
many many thanks  for reply  . now i get it . if i have 16 gb ram or 12 gb ram then maybe ok with large pages .
