### ISSUE TITLE
OSX executable do not work

### ISSUE THREAD

**Issue by pachnes** [lantonov/asmFish#134]
Hi, please could you check the macOS exectutables, they do not start. "this is not a valid UCI ...." :)

THX!
Thomas

**Comment by lantonov** [comment]
Seems that engine and GUI don't understand each other. Can you run asmFish in console and in GUI in debug mode because I don't own Mac and can't check it.

**Comment by CounterPly** [comment]
Hi Thomas,

You were correct -- the macOS executables did not work. I do not own a Mac either, and it took me a while to borrow one in order to fix this. Sorry for the delay.

In any case, this PR that should fix your issue: https://github.com/lantonov/asmFish/pull/140

Thanks for bringing this to our attention,

Justin

**Comment by lantonov** [comment]
Bugfix merged 002f9f5d222f022bede91f0ae60ba1f69bd6043d

**Comment by ghost** [comment]
My Mac .. this is the 18Mar version - where do I find the 24Mar ?

asmFishX_2018-03-18_bmi2
bench
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 253181           1150 knps       220 ms
2:      nodes: 189529           1307 knps       145 ms
3:      nodes: 103265           2024 knps       51 ms
4:      nodes: 167008           1357 knps       123 ms
5:      nodes: 77795            1095 knps       71 ms
6:      nodes: 124728           1210 knps       103 ms
7:      nodes: 170360           1191 knps       143 ms
8:      nodes: 324040           1270 knps       255 ms
9:      nodes: 333408           1190 knps       280 ms
10:     nodes: 60924            1296 knps       47 ms
11:     nodes: 169995           1062 knps       160 ms
12:     nodes: 345312           1135 knps       304 ms
13:     nodes: 93841            1144 knps       82 ms
14:     nodes: 181776           1143 knps       159 ms
15:     nodes: 94862            1264 knps       75 ms
16:     nodes: 72648            1231 knps       59 ms
17:     nodes: 57821            1521 knps       38 ms
18:     nodes: 16725            1672 knps       10 ms
19:     nodes: 80084            1906 knps       42 ms
20:     nodes: 408337           1881 knps       217 ms
21:     nodes: 74553            1911 knps       39 ms
22:     nodes: 46244            2433 knps       19 ms
23:     nodes: 107184           2748 knps       39 ms
24:     nodes: 32065            1526 knps       21 ms
25:     nodes: 17650            1604 knps       11 ms
26:     nodes: 52232            1536 knps       34 ms
27:     nodes: 295440           1678 knps       176 ms
28:     nodes: 257296           1453 knps       177 ms
29:     nodes: 72626            1320 knps       55 ms
30:     nodes: 33448            2090 knps       16 ms
31:     nodes: 38257            2732 knps       14 ms
32:     nodes: 82967            2023 knps       41 ms
33:     nodes: 50697            2204 knps       23 ms
34:     nodes: 111787           2281 knps       49 ms
35:     nodes: 98804            1619 knps       61 ms
36:     nodes: 55061            2502 knps       22 ms
37:     nodes: 306904           1598 knps       192 ms
38:     nodes: 5786             1446 knps       4 ms
39:     nodes: 19165            1368 knps       14 ms
40:     nodes: 0                0 knps          1 ms
41:     nodes: 0                0 knps          0 ms
42:     nodes: 124459           950 knps        131 ms
===========================
Total time (ms) : 3723
Nodes searched  : 5208264
Nodes/second    : 1398942

Edit : Disregard this - correct 18Mar bench below.

**Comment by lantonov** [comment]
The new version (March 23) is here:
https://github.com/lantonov/asmFish/tree/master/MacOS_binaries
I will put it also in the executables branch

**Comment by ghost** [comment]
@lantonov 👍 

Many thanks .. !!

**Comment by ghost** [comment]
24Mar version bench ..

asmFishX_2018-03-24_bmi2
bench
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 308126           2216 knps       139 ms
2:      nodes: 225126           2473 knps       91 ms
3:      nodes: 111805           3194 knps       35 ms
4:      nodes: 266748           2360 knps       113 ms
5:      nodes: 77736            1993 knps       39 ms
6:      nodes: 116304           2114 knps       55 ms
7:      nodes: 120771           2195 knps       55 ms
8:      nodes: 477793           2319 knps       206 ms
9:      nodes: 302162           2189 knps       138 ms
10:     nodes: 76542            2126 knps       36 ms
11:     nodes: 289043           2206 knps       131 ms
12:     nodes: 248496           2238 knps       111 ms
13:     nodes: 137351           2368 knps       58 ms
14:     nodes: 125631           2284 knps       55 ms
15:     nodes: 113114           2693 knps       42 ms
16:     nodes: 87135            2810 knps       31 ms
17:     nodes: 69984            3042 knps       23 ms
18:     nodes: 23899            3983 knps       6 ms
19:     nodes: 68286            4016 knps       17 ms
20:     nodes: 198681           3679 knps       54 ms
21:     nodes: 30959            3869 knps       8 ms
22:     nodes: 54968            5496 knps       10 ms
23:     nodes: 114151           4963 knps       23 ms
24:     nodes: 59923            3524 knps       17 ms
25:     nodes: 11544            2886 knps       4 ms
26:     nodes: 35514            3551 knps       10 ms
27:     nodes: 160640           2920 knps       55 ms
28:     nodes: 184138           2832 knps       65 ms
29:     nodes: 52815            2200 knps       24 ms
30:     nodes: 28674            3186 knps       9 ms
31:     nodes: 37472            4684 knps       8 ms
32:     nodes: 54769            4213 knps       13 ms
33:     nodes: 67961            4530 knps       15 ms
34:     nodes: 119230           4111 knps       29 ms
35:     nodes: 181749           3867 knps       47 ms
36:     nodes: 107830           5134 knps       21 ms
37:     nodes: 248215           3400 knps       73 ms
38:     nodes: 5734             2867 knps       2 ms
39:     nodes: 29301            2441 knps       12 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          1 ms
42:     nodes: 146487           2063 knps       71 ms
===========================
Total time (ms) : 1952
Nodes searched  : 5176807
Nodes/second    : 2652052

(I think I inadvertently benched the 18Mar version while machine was working so above posting is incorrect - empty machine bench below - sorry.)

asmFishX_2018-03-18_bmi2
bench
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 253181           2322 knps       109 ms
2:      nodes: 189529           2632 knps       72 ms
3:      nodes: 103265           3824 knps       27 ms
4:      nodes: 167008           2650 knps       63 ms
5:      nodes: 77795            2357 knps       33 ms
6:      nodes: 124728           2309 knps       54 ms
7:      nodes: 170360           2271 knps       75 ms
8:      nodes: 324040           2454 knps       132 ms
9:      nodes: 333408           2283 knps       146 ms
10:     nodes: 60924            2648 knps       23 ms
11:     nodes: 169995           2207 knps       77 ms
12:     nodes: 345312           2256 knps       153 ms
13:     nodes: 93841            2469 knps       38 ms
14:     nodes: 181776           2272 knps       80 ms
15:     nodes: 94862            2790 knps       34 ms
16:     nodes: 72648            2594 knps       28 ms
17:     nodes: 57821            3212 knps       18 ms
18:     nodes: 16725            3345 knps       5 ms
19:     nodes: 80084            4214 knps       19 ms
20:     nodes: 408337           3712 knps       110 ms
21:     nodes: 74553            4141 knps       18 ms
22:     nodes: 46244            5780 knps       8 ms
23:     nodes: 107184           5359 knps       20 ms
24:     nodes: 32065            3206 knps       10 ms
25:     nodes: 17650            2941 knps       6 ms
26:     nodes: 52232            3482 knps       15 ms
27:     nodes: 295440           3142 knps       94 ms
28:     nodes: 257296           2890 knps       89 ms
29:     nodes: 72626            2905 knps       25 ms
30:     nodes: 33448            4181 knps       8 ms
31:     nodes: 38257            3825 knps       10 ms
32:     nodes: 82967            4366 knps       19 ms
33:     nodes: 50697            5069 knps       10 ms
34:     nodes: 111787           4299 knps       26 ms
35:     nodes: 98804            3952 knps       25 ms
36:     nodes: 55061            5506 knps       10 ms
37:     nodes: 306904           3568 knps       86 ms
38:     nodes: 5786             1928 knps       3 ms
39:     nodes: 19165            2395 knps       8 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          1 ms
42:     nodes: 124459           2007 knps       62 ms
===========================
Total time (ms) : 1849
Nodes searched  : 5208264
Nodes/second    : 2816800

Something not right here - the nps for 18Mar > 24Mar.

**Comment by ghost** [comment]
macOS High Sierra
10.13.3
Intel i7

**Comment by lantonov** [comment]
Slowdown not good but happens. Might check if this is statistically significant.

**Comment by ghost** [comment]
Sounds good – thanks.
I should have posted the W10 benches too – will do that shortly.

Sent from Mail for Windows 10

**Comment by ghost** [comment]
Windows 10 System ..

asmFishW_2018-03-18_bmi2
bench
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 253181           1834 knps       138 ms
2:      nodes: 189529           2178 knps       87 ms
3:      nodes: 103265           2581 knps       40 ms
4:      nodes: 167008           2226 knps       75 ms
5:      nodes: 77795            1944 knps       40 ms
6:      nodes: 124728           1756 knps       71 ms
7:      nodes: 170360           1812 knps       94 ms
8:      nodes: 324040           1940 knps       167 ms
9:      nodes: 333408           1821 knps       183 ms
10:     nodes: 60924            2343 knps       26 ms
11:     nodes: 169995           1847 knps       92 ms
12:     nodes: 345312           1836 knps       188 ms
13:     nodes: 93841            1955 knps       48 ms
14:     nodes: 181776           1782 knps       102 ms
15:     nodes: 94862            2258 knps       42 ms
16:     nodes: 72648            2136 knps       34 ms
17:     nodes: 57821            2628 knps       22 ms
18:     nodes: 16725            2389 knps       7 ms
19:     nodes: 80084            2761 knps       29 ms
20:     nodes: 408337           3024 knps       135 ms
21:     nodes: 74553            3388 knps       22 ms
22:     nodes: 46244            4624 knps       10 ms
23:     nodes: 107184           3457 knps       31 ms
24:     nodes: 32065            2915 knps       11 ms
25:     nodes: 17650            2521 knps       7 ms
26:     nodes: 52232            2901 knps       18 ms
27:     nodes: 295440           2525 knps       117 ms
28:     nodes: 257296           2297 knps       112 ms
29:     nodes: 72626            2269 knps       32 ms
30:     nodes: 33448            2787 knps       12 ms
31:     nodes: 38257            3477 knps       11 ms
32:     nodes: 82967            3456 knps       24 ms
33:     nodes: 50697            4224 knps       12 ms
34:     nodes: 111787           2941 knps       38 ms
35:     nodes: 98804            3087 knps       32 ms
36:     nodes: 55061            4588 knps       12 ms
37:     nodes: 306904           2922 knps       105 ms
38:     nodes: 5786             2893 knps       2 ms
39:     nodes: 19165            2129 knps       9 ms
40:     nodes: 0                0 knps          1 ms
41:     nodes: 0                0 knps          0 ms
42:     nodes: 124459           1517 knps       82 ms
===========================
Total time (ms) : 2320
Nodes searched  : 5208264
Nodes/second    : 2244941



asmFishW_2018-03-24_bmi2
bench
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 308126           1913 knps       161 ms
2:      nodes: 225126           1940 knps       116 ms
3:      nodes: 111805           3194 knps       35 ms
4:      nodes: 266748           2020 knps       132 ms
5:      nodes: 77736            1943 knps       40 ms
6:      nodes: 116304           1846 knps       63 ms
7:      nodes: 120771           1654 knps       73 ms
8:      nodes: 477793           1966 knps       243 ms
9:      nodes: 302162           1756 knps       172 ms
10:     nodes: 76542            2126 knps       36 ms
11:     nodes: 289043           1751 knps       165 ms
12:     nodes: 248496           1840 knps       135 ms
13:     nodes: 137351           1760 knps       78 ms
14:     nodes: 125631           1932 knps       65 ms
15:     nodes: 113114           2262 knps       50 ms
16:     nodes: 87135            2293 knps       38 ms
17:     nodes: 69984            2120 knps       33 ms
18:     nodes: 23899            3414 knps       7 ms
19:     nodes: 68286            3103 knps       22 ms
20:     nodes: 198681           3056 knps       65 ms
21:     nodes: 30959            3439 knps       9 ms
22:     nodes: 54968            4580 knps       12 ms
23:     nodes: 114151           4390 knps       26 ms
24:     nodes: 59923            2996 knps       20 ms
25:     nodes: 11544            2308 knps       5 ms
26:     nodes: 35514            3228 knps       11 ms
27:     nodes: 160640           2262 knps       71 ms
28:     nodes: 184138           2330 knps       79 ms
29:     nodes: 52815            2400 knps       22 ms
30:     nodes: 28674            2867 knps       10 ms
31:     nodes: 37472            4163 knps       9 ms
32:     nodes: 54769            3651 knps       15 ms
33:     nodes: 67961            2831 knps       24 ms
34:     nodes: 119230           3222 knps       37 ms
35:     nodes: 181749           3304 knps       55 ms
36:     nodes: 107830           4313 knps       25 ms
37:     nodes: 248215           2668 knps       93 ms
38:     nodes: 5734             1911 knps       3 ms
39:     nodes: 29301            2253 knps       13 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          1 ms
42:     nodes: 146487           1743 knps       84 ms
===========================
Total time (ms) : 2353
Nodes searched  : 5176807
Nodes/second    : 2200087

Win10
i7-6820HK
