### ISSUE TITLE
Slowmover

### ISSUE THREAD

**Issue by Marihuanero** [lantonov/asmFish#137]
I have a question. The default setting of SLOWMOVER is 89. When i put a lower number like 50, 40 or 30 the moves are quicker, i mean it takes less time between moves. But, does this make the engine think faster or weaker? is it good to put a lower number in "slowmover" so we gain more time when playing engine to engine?...thnks for your help you are my heroes.

**Comment by lantonov** [comment]
The higher the slowmover option, the slower the engine plays and the more it thinks. This may help in longer time controls but in short time controls the engine can lose more games on time. The setting 89 is optimised for some average time control so not to lose too many games in sudden death and bullet and not to play too fast in long time controls. You can play with this setting having in mind the above.

**Comment by Marihuanero** [comment]
If the setting for slowmover is 40, this will make the engine faster but then weaker because it'll have less time to think or that depends on the hardware? i mean it doesn't lose strength if the slowmover is 40 or less

**Comment by lantonov** [comment]
With slowmover 40 the engine will be faster and weaker because it has less time to think

**Comment by lantonov** [comment]
In the newest Stockfish the Slowmover default is 84 which was obtained by tuning the TM parameters
