### ISSUE TITLE
Supposed crashes in CuteChess GUI - more information needed

### ISSUE THREAD

**Issue by CounterPly** [lantonov/asmFish#150]
So far, there has been one report of the latest asmFish (from April 1st) crashing while in the CuteChess GUI:

![image](https://user-images.githubusercontent.com/35758505/38226474-e67529ba-36c7-11e8-93c4-94362c5c236d.png)

I am still trying to reproduce this crash and was wondering if anyone else has experienced any other crashes in CuteChess (or any other GUI). 

The more details provided about the circumstances of the crash, the better (Hash size, concurrency, GUI, etc).

**Comment by CounterPly** [comment]
**Update:**
I have been unable to force a crash so far in CuteChess. I have tried various settings (hash, concurrency, TC, etc.) and all seem to be working fine on my hardware. Here are the results:

Concurrency = 18 cores
Contempt = 12 **(best setting for asmFish, always set this manually)**
Hash = 64
Threads = 1 per engine
Time = 20+0.2
Openings = 2moves_v1.pgn (Same as SF Testing Framework)
GUI = CuteChess

```
Results: 1,000 Games

1   asmFishW_2018-04-01_popcnt     +7   +221/=579/-200   51.05%      510.5/1000
2   CFish_020418_POPCNT            -7   +200/=579/-221   48.95%      489.5/1000
```

PGN: https://pastebin.com/pZsRBvrN

I will try different opening books (i.e. non-FEN based books) and hardware to see if that makes a difference.

**Comment by cirebonb** [comment]
Hi @Counterply, maybe in searchmacro code u modified something?, u can back trace historycal point of change, u should recorded before something wrong happen..

**Comment by cirebonb** [comment]
maybe its my modified code ;)

**Comment by CounterPly** [comment]
There is no problem, and everything should be working fine. The user that reported this issue was experiencing crashes unrelated to the latest patches (it was related to his prolonged use of LargePages, apparently).
