### ISSUE TITLE
Crashing after the game is finished.

### ISSUE THREAD

**Issue by ghost** [lantonov/asmFish#157]
Now this new release reads correctly the books, but it crashes at the end of the first game, on Houdini 6 (graphical interface) the following message pops-up: "Round: 1; asmFishW_2018-04-10_bmi2 caused an exception, game stopped.".

Is there any way to log the asmfish engine and reporting it here while it's playing?

**Comment by tthsqe12** [comment]
I unfortunately have not been able to reproduce crashes on win8. This looks like a job for @Counterply with win10. You have two options:
1) bisect to find the git commit that started the problems
2) trace through the code to find the exact crashing point. You can put Display 0, "here%n" to print "here" to stdout.

**Comment by tthsqe12** [comment]
I can reproduce problems with droidfish, and 1) is the only option here

**Comment by ghost** [comment]
I don't know what you mean for "bisecting to find the git commit that started the problems". I guess the most right way is showing you the process through a YouTube video. Anyway, I've tried other executables compiled by me, this happens only with BMI2 ones.

https://youtu.be/CEeDEO2K2rI?t=6m13s

Bug shown at minute 6:13 and after.

**Comment by CounterPly** [comment]
@massimilianogoi 
I haven't had any problems with the bmi2 builds yet myself, but I will try to reproduce this crash tomorrow based on the video you have provided. 

Does it also fail when you use [this bmi2 executable](https://github.com/lantonov/asmFish/raw/master/WindowsOS_binaries/asmFishW_2018-04-11_bmi2.exe)?

**Comment by ghost** [comment]
Yes!! I'm surprised! Settings used: last Cerebellum as polyglot book, syzygy probe depth: 2, #threads: 8 (the maximum possible as hyperthreaded quadcore processor).

**Comment by CounterPly** [comment]
I have been unable to reproduce this bug on Windows 10 (I have tried it on 4 separate bmi2 processors, with no issues.) Perhaps @lantonov would have more luck. 

@massimilianogoi Can you tell me the exact commit number where you started noticing these crashes on your system?

**Comment by ghost** [comment]
I guess three weeks ago or something. I already posted about a similar issue but the thread was closed. Check between the closed issues: from that moment asmFish BMI2 had issues on my computer, no other engines had issues or even the same issue, neither the other asmFish versions. It's something related to the BMI2 executable.

**Comment by ghost** [comment]
Now the error happens also in the asmFishW_9_popcnt executable of this package: https://github.com/lantonov/asmFish/releases. This issue is only Chessbase GUI related. Tried them with Arena, they perfectly works.

**Comment by CounterPly** [comment]
Strange. If you have an older ChessBase product version, I would highly recommend (a legitimate purchase of) Fritz 15+ as that seems to be working perfectly for the vast majority of users with bmi2+popcnt processors using the latest asmFish versions. Outside of this, we unfortunately have no way to correct your crashes as you seem to be the only one capable of reproducing them. Until either (1) someone else who can replicate this crash comes forward with more details, or (2) until you conduct the git bisections recommended by Moha, there is really nothing that can be done at this time.

**Comment by CounterPly** [comment]
Update: Try unchecking large pages when setting up the engine. Some users have recently reported that this has been the cause of crashes on their systems. For some reason, LP is causing issues for some in the Fritz/CB GUI.

**Comment by CounterPly** [comment]
@massimilianogoi 

Please refer [**here**](https://github.com/lantonov/asmFish/issues/160) for further support on this issue.
