### ISSUE TITLE
posdraw detection

### ISSUE THREAD

**Issue by cirebonb** [lantonov/asmFish#159]
asmfish will going faster if posisdraw detection on searchmacro and qsearchmacro moved to move_do and move_do_null, no functional change, no differ in bench, but increase n% on speed. ex.

call move_do
test ecx, ecx ;pos is draw?
jz .undo_move
;pruning
;search nonpv with reduction depth
;search pv with red depth
,search pv with normal depth

.undo_move:
mov ecx,dword[.move]
call move_undo

nah?

**Comment by cirebonb** [comment]
I just allready did it, change in uci.asm especially posisdraw func, change in search macro especially in state.pv initialize, move_do_search, move_do_probcut,move_donull, move_do.asm adding posisdraw at end/right after setcheckinfo, move_do_null.asm at end before setcheckinfo, and thereis code on uciparsemove with mention setcheckinfo twice, I strip one code call setcheckinfo right after move_do_uciparsemove, and tested it on intel i7 2,2, its extremely fast..., reaching above 5million nps on drawish endgame,

**Comment by cirebonb** [comment]
my plan in near future with permission of God, I will add queen mate detection on evaluation, evaluation will provide VALUEMATE-ONEPLY, this issue should be consider as prority, because in some cases, asmfish need much time to find solution in test ex. wac.epd, but actually I didnt have much time to spend, this is my problem, not you guys.

**Comment by cirebonb** [comment]
![tested](https://user-images.githubusercontent.com/36750431/38803238-c48c8b32-4198-11e8-9aa2-658a71c6646c.jpg)
"Its Not Fair",

**Comment by Ipmanchess** [comment]
That's very nice..can i test your asmFish version ;)

**Comment by cirebonb** [comment]
Allready tested.
   Engine        Score                                                                                As                                                                               AS    S-B
1: AsmFishW_rev  44,0/80 ???????????????????????????????????????????????????????????????????????????????? ====1=1=101010====0=1==0=1=====0===0=0==1===11====1==1====1=1==0=0====1==0==1111  1584,0
2: ASMSF180313vk 36,0/80 ====0=0=010101====1=0==1=0=====1===1=1==0===00====0==0====0=0==1=1====0==1==0000 ????????????????????????????????????????????????????????????????????????????????  1584,0

80 games played / Tournament is finished
Name of the tournament: Rev_VS_VK2
Site/ Country: HUBINSYAKER-GM, Indonesia
Level: Blitz 0:30/0,4
Hardware: Intel(R) Core(TM) Duo CPU      T2450  @ 2.00GHzDual  2000 MHz with 504 MB Memory

**Comment by Ipmanchess** [comment]
here it would be on a i9 7980XE @4.2Ghz 18cores/36threads..

**Comment by cirebonb** [comment]
dont worry, the picture is fake, ASMSF180313vk not ready in critical time bro... do it just for fun. thanks Ipmanchess, i still improve this source code just like imention above...

**Comment by Ipmanchess** [comment]
If it's fake?..why you put it here then on Github??

**Comment by cirebonb** [comment]
walla... it just 7 game
https://www.dropbox.com/s/pls6e9m8axy9ima/asmFish-eng-rev.rar?dl=0
if you insist, i just compile, i think stable old version. good luck, ;)

**Comment by cirebonb** [comment]
im not ready post source code, because I have not include latest patch, and so much dirty, not structured code
