### ISSUE TITLE
when hastable size 1024 or 2048 caused an exception

### ISSUE THREAD

**Issue by sohel1214** [lantonov/asmFish#161]
testing engine 2 game then show Round: 1; asmFishW_9_popcnt caused an exception, game stopped.
but 512 hastable with large pages ok no problem . with large pages  hastable1024 or 2028 sow error. without large pages ok with  hastable 1024 or 2024 no error. my windows 64 bit.  
pls check

**Comment by CounterPly** [comment]
@sohel1214 

Thanks for reporting this. Just to confirm, is this with the newest asmFish 9 executables that were posted yesterday?

**Comment by sohel1214** [comment]
i check again 2 days ago latest releases asmFish 9 ok now.
