### ISSUE TITLE
 100 GB ctg book (question)

### ISSUE THREAD

**Issue by sohel1214** [lantonov/asmFish#170]
can asmfish read 100GB ctg book  ? if not then its possible to make it ?

**Comment by lantonov** [comment]
CTG is a Chess Base book format. asmFish can use CTG book if it's loaded in some of Chess Base GUIs (e.g. Fritz) but not as an engine's own book. The own book format of asmFish is BIN. AFAIK, there are no plans to exchange BIN for CTG or add CTG as alternative engine book format. This is possible but requires a fair amount of coding.

**Comment by MichaelB7** [comment]
In addition, ctg is a proprietary format so decoding and then publishing the proprietary format is not an endeavor that  open source Github would naturally endorse.

**Comment by sohel1214** [comment]
ty for ur reply. how can we make bin book ......... any easy soft name give us  pls

**Comment by MichaelB7** [comment]
All you need is polyglot and a large pgn file - there are plenty of resources that explain - google “polyglot opening book chess”.  Some gui’s support it as well as asmfish directly.
