### ISSUE TITLE
asmfish next ver  with 7 man Tablebases ? ( question)

### ISSUE THREAD

**Issue by sohel1214** [lantonov/asmFish#171]
#

**Comment by CounterPly** [comment]
`if USE_SYZYGY = 1 & SevenPieces = 0`

`   mov   eax, dword[rbx+Dev.tthsqe12]`
`   or    eax, dword[rbx+Dev.syzygy1]`

`   _popcnt  rax, rax, rdx`

`   test     eax, eax`
`     jz     .waitPatiently`

` mov    rsi, qword[rbx+Syzygy.sevenPieceTables]`
`   ret`

`end if`

(**Translation:** Hopefully, soon. It is best to leave this particular task for @tthsqe12 or @syzygy1 ).

**Comment by sohel1214** [comment]
ty for ur reply
