### ISSUE TITLE
General Updates/Questions

### ISSUE THREAD

**Issue by double-beep** [lantonov/asmFish#174]
Hello @lantonov and @Counterply,
I have the following questions:

1. Why Matefinder hasn't got base executables?
2. Executables branch is out-of-date with the default branch. Can you ask @lantonov, to update it?
3. Description says that latest version is `11.05.2018`. Can you ask @lantonov, to update it? Wiki has the same problem, too!

- [ ] Update description (@lantonov  must do this)
- [x] Update wikis
- [x] Support Matefinder base executables
- [x] Update executables branch
Thanks!

**Comment by CounterPly** [comment]
Hi double-beep,

Thanks for staying on top of these action items. I added support to make.bat for Matefinder base executables in the latest commit and included mateFish_base executables for all operating systems. I'll also take a look at the other executables branch shortly to see if I can get it caught up to the master branch.

I am certain Lyudmil will get around to updating the description. The last I heard, he was under some non chess-related work deadlines, but I have no doubt he will be back soon.

**Comment by double-beep** [comment]
Hi @Counterply,
I saw that you did large changes in the make.bat; (timings are very good) and you added support to base matefinder executables. Thanks!

> I am certain Lyudmil will get around to updating the description. The last I heard, he was under some non chess-related work deadlines, but I have no doubt he will be back soon.

I hope that he will come soon. I hope the same with @tthsqe12, also, who has left(?) github about a month ago. @tthsqe12 is very good in assembly and asmfish will catch Stockfish soon!

**Comment by CounterPly** [comment]
Don't worry, neither of them has left. Moha will be back eventually. He contributed *a lot* of invaluable commits during his last activity streak, so he is on a well-deserved break at the moment.

**Comment by double-beep** [comment]
Ok @Counterply, I don't worry!

**Comment by CounterPly** [comment]
Updated executables branch with the latest binaries.

**Comment by ghost** [comment]
Needless to say (I've said it before somewhere else with a different nick) you've done and are continuing to do a fabulous job.

**Comment by double-beep** [comment]
Opened a pull request (see above (#176)) which compares @Counterply's branch and @lantonov's branch.

**Comment by double-beep** [comment]
@Counterply, can you explain me what's exactly the difference between asmfish and matefish?

**Comment by CounterPly** [comment]
Matefish is based on the branch "mate_finder" by @jhellis3. It is ideal for analyzing complex and/or tactical positions where your intuition tells you: "there is probably a mate here." 

For a more clear idea of what this entails, check out the following branch-comparison: 

https://github.com/official-stockfish/Stockfish/compare/master...jhellis3:mate_finder

**Comment by double-beep** [comment]
Hello, @Counterply, thanks for the explanation. I asked because when I open the mateFishW*.exe file I get:
`asmFishW_2018-06-05_base`
which is the same with asmFishW*.exe.
I know that benches are different, but ChessBase cannot understand that asmFish and mateFish are different.
I press `Create UCI engine` and I select the asmFish*.exe. I set the parameters and press `OK`. When I do the same with mateFish*.exe ChessBase shows a message tht says: `asmFishW_2018-06-05_base already exists`! 
Analytically (with screenshots) we have:

- asmFishW*.exe import
![cbase_asmfish](https://user-images.githubusercontent.com/38133098/40973425-dd3886c6-68cc-11e8-9336-ca98a11980a1.jpg)

- mateFish*.exe import
![cbase_matefish](https://user-images.githubusercontent.com/38133098/40973479-09637ecc-68cd-11e8-84ae-24082293a488.jpg)

- and finally the error I get after mateFish*.exe import
![cbase_error](https://user-images.githubusercontent.com/38133098/40973507-249f3b04-68cd-11e8-92b8-558028cc7d27.jpg)

How can be this solved?
Thanks!
@double-beep

**Comment by CounterPly** [comment]
There are several ways to prevent this from happening. 

1) Delete the corresponding ".uci" file on your system and make a new engine. I would recommend [this program](https://download.cnet.com/Everything/3000-2379_4-10890746.html). Simply type in "*.uci" (without the quotes) and it should bring you directly to the location of the file on your system.

2) Assemble your own mateFinder with a different name of your choosing.

3) In the name field of your engine in the picture you provided (preferably, after you have set the parameters), add in "_mf" in order to give matefinder a distinct identity. Note: this must come *after* the engine name (i.e. you cannot edit the engine's name itself; you can only append to it). 

One thing to keep in mind is that engines beginning with the word "mate" are not allowed in Fritz/Chessbase. I have no idea why this is, but that's the way it used to be. Perhaps they have fixed this bug in newer editions of Fritz, but I have not checked.

**Comment by double-beep** [comment]
Hello @Counterply 
> Delete the corresponding ".uci" file on your system and make a new engine.

What do you mean and how this can be done?
> Compile your own mateFinder with a different name of your choosing

How can I do this? With the make.bat?

> One thing to keep in mind is that engines beginning with the word "mate" are not allowed in Fritz/Chessbase. I have no idea why this is, but that's the way it used to be. Perhaps they have fixed this bug in newer editions of Fritz, but I have not checked.

I think that this is not related with `already exists`, but ok.

**Comment by double-beep** [comment]
But how do you explain the name `asmFishW*_base.exe` in the matefinder file?
Anyway, the 3rd way worked!
Thanks!

**Comment by double-beep** [comment]
Anyway, the 3rd way worked!

**Comment by double-beep** [comment]
@Counterply, I have done all the executables since "Tweak time management" [here](https://github.com/Help-batch/asmFish/tree/executables). Should I open a pull request? Or you will update?

**Comment by CounterPly** [comment]
Hi double-beep,

I'm glad (3) worked; it is the most straight-forward method. 

> What do you mean and how this can be done?

I mean, delete the .uci file physically from disk and then use Fritz to set-up a new engine. This is a particularly useful trick only if you have to phase-out a lot of old/obsolete engines.

> How can I do this? With the make.bat?

No, that would just change the executable name, not the engine's internal name. You would need to modify the source first and then reassemble (with make.bat).

The lines you need to change are in MainData.asm (lines 38-47).
![image](https://user-images.githubusercontent.com/35758505/40996738-96cc1c76-68d0-11e8-9613-47259283c87a.png)

> I think that this is not related with already exists, but ok.

I know, I was just warning you. I once wasted a lot of time trying to figure out why mateFinder wasn't loading, and it was ultimately ChessBase's problem and not the engine's. 


> But how do you explain the name asmFishW*_base.exe in the matefinder file?

Most likely a mistake on my end. I'll take a look and fix it with my next commit. Thanks for letting me know.

**Comment by CounterPly** [comment]
> I have done all the executables since "Tweak time management" here. Should I open a pull request? Or you will update?

Thank you, this was very helpful. I created a PR for you and merged it to the executables branch.

**Comment by double-beep** [comment]
Hi Justin!
Thanks for the explanation and the pull request, your welcome for the executables!

> The lines you need to change are in MainData.asm (lines 38-47).
"image"

Could you give me an example?

> I mean, delete the .uci file physically from disk and then use Fritz to set-up a new engine. This is a particularly useful trick only if you have to phase-out a lot of old/obsolete engines.

Do you know the usual location of the *.uci?

**Comment by double-beep** [comment]
The only things that keep this issue open are the update of the description, the wiki (which means that @lantonov will come to help) and also @tthsqe12 come, also! 
Asmfish is very fast (🥇 ), but assembly is hard. So asmfish is back. I don't feel good with that!

**Comment by double-beep** [comment]
Hello @Counterply,
In your previous comment with the example, you showed me how I can add sth to the end of the engine's internal name. I mean that you showed me how to change a name from `asmFish_%datestamp%_%VERSION_POST%` to `asmFish_%datestamp%_%VERSION_POST%_mf`. Is there a way to change name from `asmFish_%datestamp%_%VERSION_POST%` to another name? e.g. `mateFish_%datestamp%_%VERSION_POST%`? I would be happy if possible! 👍 :))

**Comment by double-beep** [comment]
@Counterply, do you know @lantonov and @tthsqe12? Have you ever met? Or just simple with github you learnt each other?

**Comment by double-beep** [comment]
Do you know when @lantonov and @tthsqe12 will return, @Counterply?

**Comment by CounterPly** [comment]
--------

> **"Do you know the usual location of .uci?"**

For me it is located at: `C:\Program Files (x86)\Common Files\ChessBase\Engines.uci`

--------

> **"Asmfish is very fast, but assembly is hard. So asmfish is back. I don't feel good with that!"**

Sorry, I am not sure what you are trying to say here. Do you have concerns about a certain commit?

--------
> **"Is there a way to change name from [...] to another name?"**

This modification in MainData.asm should do what you want:

<img src="https://i.gyazo.com/efe53ae158e05985c1dc1266ed9e70fa.png" width="30%" height="30%"/>

--------

> **"Do you know when @lantonov and @tthsqe12 will return, @Counterply?"**

No, I do not know when Lyudmil and Moha will be back. I imagine they are both busy with other endeavors, but they'll be back eventually.

--------

**Comment by double-beep** [comment]
> For me it is located at: C:\Program Files (x86)\Common Files\ChessBase\Engines.uci

I couldn't find any *.uci files. There are only *.engine files

> This modification in MainData.asm should do what you want:
> <Image>

It works! Could you do it in next commit?

> No, I do not know when Lyudmil and Moha will be back. **I imagine** they are both busy with other endeavors, but they'll be back eventually.

Sorry, I thought you knew them.

**Comment by CounterPly** [comment]
No worries. Sure, I made a note to fix that as well in the next commit. Could you verify for me that "mateFinder" (as an engine name) is functional in Fritz and/or Chessbase?

**Comment by double-beep** [comment]
Hello Justin,
Something strange happens with the code you showed me in the last comment. (Note that this 'bug' happens only with that code [not the previous one at commit cb7c53d]).
I press `Create UCI Engine`. I insert the executable and press `OK`. (The name is ok, [mateFish]). When I press `Add kibitzer` no engine named matefish exists! But if I press `Engine Management` I can see mateFish in active engines!
Does this seem strange to you, also?

**Comment by CounterPly** [comment]
Yes that is what I was referring to 3 days ago with the following messages:

> **Counterply:** "One thing to keep in mind is that engines beginning with the word "mate" are not allowed in Fritz/Chessbase. I have no idea why this is, but that's the way it used to be. Perhaps they have fixed this bug in newer editions of Fritz, but I have not checked."
>> **double-beep:** "I think that this is not related with already exists, but ok."
>>> **Counterply:** I know, I was just warning you. I once wasted a lot of time trying to figure out why mateFinder wasn't loading, and it was ultimately ChessBase's problem and not the engine's.

**Comment by CounterPly** [comment]
So seeing as that bug isn't fixed yet by ChessBase, I will leave the names as they currently are (i.e. with the _mf suffix). Perhaps consider contacting the ChessBase team and asking them to fix this bug.

**Comment by double-beep** [comment]
I have reported this to ChessBase. Maybe that bug is fixed but in ChessBase 14.

**Comment by double-beep** [comment]
> (i.e. with the _mf suffix).

@Counterply, this confuses me. Why not renaming to mFish...?

**Comment by double-beep** [comment]
For the CB bug I got an the following answer:
> Peter Schreiner (ChessBase)
11 Juni, 09:03 EEST
Hello,
thank you very much for your email.
I forward a copy of your email to our developer team!
Kind regards
-Peter Schreiner

I will notice you if newer.

**Comment by double-beep** [comment]
Starting from line 40:
`    db 'mFish'`
`    db VERSION_OS`
`    db '_'`
`    BuildTimeData`
`    db '_'`
`    db VERSION_POST`
`  else`
`    db VERSION_PRE`
`    db VERSION_OS`
`    db '_'`
`    BuildTimeData`
`    db '_'`
`    db VERSION_POST`
` end if`
and ending in line 53.
If this is correct, could you commit it with my notes in pull request #183?

**Comment by double-beep** [comment]
Thanks for applying. This issues has changed the things in asmFish a lot!

**Comment by double-beep** [comment]
Hi @Counterply. @tthsqe12 came back to github and updated cas! I hope he will come soon.

**Comment by double-beep** [comment]
@Counterply, `BuildTimeData` is standard or changeable? If I can change it where can I do it?
[Note: No newer from ChessBase 👎 ]

**Comment by CounterPly** [comment]
`BuildTimeData` is a custom macro. It is defined in [BasicMacros.asm](https://github.com/lantonov/asmFish/blob/master/x86/BasicMacros.asm), starting at line 72.

**Comment by double-beep** [comment]
ThanksALot! I hope that it ends at line 101 at the command `end macro`.

**Comment by double-beep** [comment]
Hi @Counterply,
I have to offer something, just for your time and your computer. Why not letting AppVeyor do the work for you? I have tried it in my repository and it's amazing! AppVeyor builds the executables quickly and then presents them. Ah, yeah, you can also customize it to give the bench after the build without downloading it.! I have created a file named `appveyor.yml` in my repository which says AppVeyor how to build the repository. You are free to edit it and add it to your fork. If you want any help, I am here.
@double-beep

**Comment by TasicV** [comment]
Hi,
I have question about TTFILE. I see this file crate engine, but where and how. Is this file temporary, or like arhive file. Also in parameters you have SAVETTFILE, but I cant see any hash or other file in folder. Can you explain this parameter please?

**Comment by double-beep** [comment]
Hi @TasicV,
The path must be FULL and include the TTFILE filename. For example: `D:\TTFILE\**TT.hsh**`. Then, press TTSave. When you want to load it to the same. I don't know if I am true 🤔 , but this works in my computer. @Counterply will confirm that! 🌞

**Comment by TasicV** [comment]
I make it alone to save file before you told me, but thank you very much. Also I must ask you then why this file in start is 4 GB?? Is this normal?

**Comment by CounterPly** [comment]
@TasicV 

Yes that is normal. For example, if your hash setting was 4 GB and you allowed it to fill to 100% prior to saving, then your .hsh file will be 4 GB in size. If you set it to 32 GB, it will be 32 GB. Etc.

**Comment by double-beep** [comment]
Hi @Counterply,

There's a problem after commit d8ad316 in the `gh-pages` branch only as you stored all the files in *.7z and now website lantonov.githu.io/asmFish isn't working.
As you also stored the old binaries in the executables branch I will put the **in** the 7-zip file or **in the folder**?

**Comment by CounterPly** [comment]
I'll fix gh-pages, thanks for letting me know.

7-zip file would be ideal. Git isn't meant to be hosting so many binaries (it slows things down).

**Comment by double-beep** [comment]
Yes, your idea was great, but **where** should I put the executables?

**Comment by CounterPly** [comment]
Putting them in a 7-zip file would be ideal.

**Comment by double-beep** [comment]
Thanks! I opened #198

**Comment by double-beep** [comment]
@Counterply Can you edit wikis?

**Comment by double-beep** [comment]
I am asking that as I have ready the wikis [here](https://github.com/double-beep/asmFish/wiki/Suggested-change-log-for-lantonov-asmFish-wiki). I am preparing an another version at the moment. You can review them when you have time.

**Comment by double-beep** [comment]
I have prepared the version [here](https://github.com/double-beep/asmFish/wiki/Another-version-for-change-log). I think I have put some extra details. What do you think?

**Comment by CounterPly** [comment]
@double-beep This looks phenomenal; thank you for taking the time to do that. I am traveling at the moment, but I will update the wiki with your contributions as soon as I am back later this evening.

**Comment by double-beep** [comment]
@Counterply your welcome! :)

You said you 'll have return by the evening and  in my country now it's night! Just curious, what is your time zone? Mine is UTC + 3

**Comment by CounterPly** [comment]
UTC -5

**Comment by CounterPly** [comment]
Updated change-log to your last version.

**Comment by double-beep** [comment]
Hi, @Counterply,
thanks for the wiki update. I think here, you should add a suggestion label :).
Sorry for the "inertia" the last ~3-4 days; I am in a hotel with poor internet connection playing a national chess tournament. I should never forget my chess obligations :-).

I really think that option `U - Update fasmg.exe` is not required. The thing you can do, is to tell make.bat to automatically update fasmg.exe in the beginning.

Question: Only `fasmg.exe` is updated with the `download.vbs` file or both `fasmg` and `fasmg.exe`?

By the way, the title seems great to me :-).

Could you let me prepare the easy patch `Tuned some values...` or you can do it?

I will prepare wiki's change-log soon. How did you make the latest 'updater' me? (double-beep)
@double-beep

**Comment by double-beep** [comment]
Hi, @Counterply,
thanks for the wiki update. I think here, you should add a suggestion label to this issue :).
Sorry for the "inertia" the last ~3-4 days; I am in a hotel with poor internet connection playing a national chess tournament. I should never forget my chess obligations :-).

I really think that option `U - Update fasmg.exe` is not required. The thing you can do, is to tell make.bat to automatically update fasmg.exe in the beginning.
Question: Only `fasmg.exe` is updated with the `download.vbs` file or both `fasmg` and `fasmg.exe`?

Could you let me prepare the easy patch `Tuned some values...` or you can do it?

I will prepare wiki's change-log soon. How did you make the latest 'updater' me? (double-beep)
By the way, the title seems great to me :-) and your idea about benching armFish with TRAVIS which supports qemu. You could make a script after, to bench Mac and Linux, as Travis supports them, also.
@double-beep

**Comment by CounterPly** [comment]
- I initially had it as updating fasmg at the beginning like you suggested, but I quickly found that to be annoying and unnecessary considering fasmg is only updated once every few months (usually). I think leaving it as an option for the user is an effective compromise that doesn't waste time every round of assembly.

- As written in the output message, only fasmg.exe is updated.

- Yes, please be my guest if you want to help contribute to the patches. It is very hard being the only one working on asmFish at the moment, so all help is VERY appreciated.

- All patches on the lantonov repository must be in order but [bit.ly/asmFishCP](http://bit.ly/asmFishCP) can be updated at anytime, in any order. We will get to them here eventually, too, so no effort is wasted.

**Comment by CounterPly** [comment]
- I used `git commit --amend --author="Author Name <email@address.com>"`

- I have been thinking about qemu, and I think the best way to go about doing this is via Docker. Someone posted a thread a while back in which they sucessfully set up a Docker container for asmFish so that could be a great starting point.

- Good luck in your chess tournament!

**Comment by double-beep** [comment]
Hi @Counterply, I saw your messages, I was busy with training. I will complete the patch today as the tournament ends! Instead of waiting please try what you said above about benching armFish with a dockerfile.

**Comment by CounterPly** [comment]
It is fine. I already completed the patch along with 7 others. I will commit them here once the arm versions are complete.

**Comment by double-beep** [comment]
Hello @Counterply,
1. make.bat is broken. No reason to remove the 1 of 2 `start /min /wait` in `:allBinaries`.
2. I have prepared the wiki.
3. Newest fasmg is faster after a test in AppVeyor console.
4. I think we should ask @ksylvan for a docker command to bench the engines if you do not know any. You can see my work in the [dockerhub](hub.docker.com/r/doublebeep/asmfish-build1/builds) and generally explore the repository (you can join hub.docker.com if you haven't done it and I will make you a collaborator) and [in branch docker in my fork](https://github.com/double-beep/asmFish/tree/docker).
@double-beep

**Comment by CounterPly** [comment]
I deleted those lines because it saves several seconds when I assemble locally. Since it breaks make.bat for your system, however, I will put it back during the next commit.

**Comment by CounterPly** [comment]
Thanks for looking into Docker. I will create an account soon.

**Comment by cirebonb** [comment]
Hi @Counterply, when I look code at move_do_null, I see in line 25 "mov edx, dword[rbx+State.epSquare]", why just "movzx edx, byte[rbx.State.epSquare]", this line neglect value of capturedpiece that we used on updatestat, other than we keep copying it new State with different possidetomove.

**Comment by double-beep** [comment]
Hi @cirebonb, this is not correct:
```
flat assembler  version g.i88rw
x86\fish.asm [173] x86\Move_DoNull.asm [25]:
        movzx edx, byte[rbx.State.epSquare]
macro movzx [2] macro parse_operand [5] macro parse_operand_value [21] macro parse_address [13]:
        ns.address = +addr
Processed: @src.address = +rbx.State.epSquare
Error: symbol 'epSquare' is undefined or out of scope.
```
This is a problem in compilation after command:
```
fasmg.exe "x86\fish.asm" "asmFishW_base.exe" -e 1000000 -i "VERSION_OS='W'" -i "PEDANTIC = 1" -i "VERSION_POST = 'base'" %debug%
```

**Comment by double-beep** [comment]
@Counterply,
there is again a newer version of fasmg.exe, g.i8nim. I am testing at the moment.

------------------------------------------------------------------------------------------
EDIT
----------------------------------------------------------------------------------------
Newest version is about 50 seconds faster.

**Comment by cirebonb** [comment]
hi @doublebeep not [rbx.State.epSquare] but [rbx+State.epSquare]

**Comment by cirebonb** [comment]
not @doublebeep but @double-beep

**Comment by CounterPly** [comment]
@cirebonb 

Unless I misunderstood your original question, zero-extending byte[rbx+State+epSquare] into rdx alters the bench from the correct value of 4777674 to an incorrect value of 4843129. This is due to partial-hammering of the edx register, which I don't think is particularly desirable here. Even if it was, however, this branch is for official bench-match versions only.

**Comment by double-beep** [comment]
@cirebonb, sorry for that, of course we cannot say `rbx.State.epSquare`; I didn't take a further look.

@Counterply as about the dockerfile, I am experimenting with it the last 4 days, but I could not find a command to bench the executables. Any ideas? And by the way what is your username in dockerhub?

**Comment by cirebonb** [comment]
yes, sorry my mistake

**Comment by CounterPly** [comment]
@double-beep

Thank you very much for looking into it. Sorry for being unresponsive these past few days; I have been under several work-deadlines and have not had much free time. 

I made an account on DockerHub -- CounterPly.

**Comment by double-beep** [comment]
Hello, @Counterply it is ok.
I have created a repository [here](https://hub.docker.com/r/asmfish/official-asmfish/). I use as `SOURCE_REPO` my fork as there I got the dockerfile. You have admin access, you can change it when you want.

---
The last days I was trying to find a command to bench the executables. [Note: Server there, assembles the executables very slow (~60-80secs). You can see the logs.] The one that had to work was:
```
&& ./armFishL_v8 bench
```
Unfortunately, I got a message: `Access is denied` and build failed. If you know docker well, as I do not know, can you help?

**Comment by double-beep** [comment]
Hello, there is a newer version of fasmg once again: 
flat assembler g i8q67

----
Results of my testing:
flat assembler g i8q67 is slower that g.i8nim -> ~4seconds per build and totally 2minutes(!) slower, so I think this version should not be included in asmFish.

**Comment by double-beep** [comment]
Hello, Justin
Based on your work I have prepared patches until
`Simply reset statScore to zero at beta cutoff`. You can merge this to master. Also, I have fixed make.bat.
Will you implement the "cuckoo" patches?
Fasmg.exe when is open with start /min build ALL the executables or just first e.g. 4 per time?

I may not have the time to upload my work on the latest patch as I am going on holiday in a mountain. I will not have access to my laptop for the next 7days.

**Comment by double-beep** [comment]
flat assembler g i960e is the newest version of fasmg. Testing at the moment and will respond later.

----
# Results

At total, version i960e is ~10secs faster. I think this version **should be included**. 

------
Will patches:
- Use cycle detection to bound search value and
- Simplyfying away the progressKey 
be implementer???

If not, when asmFish's and stockfish's benches will realign?

**Comment by CounterPly** [comment]
Sorry for the late reply. 

Thank you for testing. I will update fasmg with the next functional patch.

Yes, the cuckoo patches will be implemented eventually. I have been working on them over the past week whenever possible, but I have been very busy lately at work and have not had much time to do patches. (I may or may not need @tthsqe12 's help on this one, but honestly, I haven't given it a complete enough of an attempt to say for sure).

Since the cuckoo patches will probably take a while to get right, I've decided to also continue implementing subsequent functional patches on my asmFish fork while official progress is on pause (for those users who would be interested in these). Currently, it is a few patches ahead of the official branch and should be at least marginally stronger.

**Comment by double-beep** [comment]
Hi,

Except the change I offered for make.bat in issue #211, I have some more simplifications. Especially in :allBinaries (and in other labels of course) you always specify
```batchfile
set include=x86\include\
```
Why just
```batchfile
:allBinaries
set include=x86\include\
```
and delete the same command in this label? (except when you specify set include=arm\include\). This can be done with other labels of course.

Some `move` commands need simplification in make.bat also. Take a look please if you can.

**Comment by CounterPly** [comment]
Noted. I will look at it during the next asmFish commit.

A general comment though: I don't think make.bat is important enough to justify rigorous optimization. It is fine if you want to spend your spare time tweaking it, but remember that most people shouldn't even need to use it anyway since binaries are assembled with every commit. 

Remember, it isn't a chess engine that evaluates millions of nodes per second. It is a batch file. Eliminating an extra move command here or there will probably only save nanoseconds -- if that.

Thank you for your dedication, though. It is much appreciated.

**Comment by wisecam** [comment]
Hello Asmfish Team,
Could you please update us if it is time to mourn the death of AsmFish?
I hope it is not

**Comment by NiTeFiSe** [comment]
@wisecam 

no its not dead. they posted an update on other forums and counterplys branch is still a bit active with some extra patches every once in a while

source:
http://immortalchess.net/forum/showthread.php?t=32349&page=29
http://mzchessforum.altervista.org/viewtopic.php?f=31&p=28810#p28810

**Comment by double-beep** [comment]
@Counterply
@lantonov came back to github and updated his fork of stockfish. Hope he has the time to 'see' asmFish.

**Comment by mausalimi** [comment]
this project is falling more and more behind sadly. ah well.

/edit: see below.

**Comment by CounterPly** [comment]
@mausalimi As previously stated by others here, please refer to my fork for the time being until I can get the cuckoo tables working properly. It contains all patches through early July 2018 and will soon be caught up to the month of August. As soon as the cuckoo patch is complete, the benches will be once again perfectly realigned and I will begin moving patches back over to this repository.

**Comment by CounterPly** [comment]
I am closing this thread since it has grown quite long and difficult to navigate. Special thanks to @double-beep for all of the excellent topics/questions/responses provided here.

(Moving forward, it will probably be easiest for everyone to maintain all questions/concerns as separate issues/topics).
