### ISSUE TITLE
Correspondence Chess

### ISSUE THREAD

**Issue by asmfishcc** [lantonov/asmFish#18]
Would it be possible to realize (ex.) **CorASM** (CorChess: http://chess.ultimaiq.net/corchess.html and http://chess.ultimaiq.net/cc_in_detail.htm), i.e. ASMFish for **correspondence chess**? It would be very helpful! Thank you!!

**Comment by lantonov** [comment]
There are a lot of good ideas and a big scarcity of asm programmers to put them to practice. Correspondence chess (aka deep-thinking chess) is a goal to many, including SF developers.
As concerns the concrete idea in ultimaiq, it was tried a couple of months ago in FishTest and failed SPRT. As you see, it fails the tests also on ultimaiq (4-5 Elo loss). About the second page (the "details"), it is just a bunch of math formulas which follow from nowhere. There simply isn't any sense to apply those to the SF code.
