### ISSUE TITLE
Cannot find FASMG to make a compile

### ISSUE THREAD

**Issue by Sportsmen** [lantonov/asmFish#211]
Just downloaded the latest ASM. When I extract I see FASMG. I double click on make I see the normal screen. 

If I click B
=== Building Windows BMI2 Executable ===
The system cannot find the file specified.

If I click 2
Windows cannot find FASMG.EXE

**Comment by CounterPly** [comment]
Did you select make-all and not let it finish to completion? There must be a pre-existing bmi2 version present in WindowsOS_Binaries for the script to work properly.

This will probably also fix option 2, but if not, make sure you are in the correct directory.

Let me know if you still have problems and I'll take a look in a few hours.

**Comment by Sportsmen** [comment]
Hello

Uusally all I do is download the file, unzip it, click on make and select B to get a BMI compile. Never had an issue before. This time it gives me an error and does not make the BMI or any compile

**Comment by CounterPly** [comment]
Very strange. Do you know at which commit this stopped working for you?

One possibility could be that the newer version of fasmg.exe is getting auto-removed by your antivirus since it is a relatively new executable that few users have downloaded.

**Comment by Sportsmen** [comment]
Hello

The last download I have is 7 9 18. This one worked great. The only anti virus I have is windows defender. It was a strange problem asm usually works great. 
--------------------------------------------
On Thu, 7/26/18, Justin Dehorty <notifications@github.com> wrote:

 Subject: Re: [lantonov/asmFish] Cannot find FASMG to make a compile (#211)
 To: "lantonov/asmFish" <asmFish@noreply.github.com>
 Cc: "Sportsmen" <sportsmen2005@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Thursday, July 26, 2018, 12:21 PM
 
 Very strange. Do you know at
 which commit this stopped working for you?
 One possibility could be that the newer version of
 fasmg.exe is getting auto-removed by your antivirus since it
 is a relatively new executable that few users have
 downloaded.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by double-beep** [comment]
Hello @Sportsmen and @Counterply,

It is really strange that this happened. This errror, as @Counterply said, may happened because the script either terminated suddenly or (as make.bat is broken in option `1` you didn't let make.bat finish assembling. One other option is that you selected `U` and fasmg.exe was deleted, but download.vbs couldn't download the fasmg.exe file.

@Sportsmen,
what you wrote
# (

> If I click B
=== Building Windows BMI2 Executable ===
The system cannot find the file specified.

is the exact "screenshot"? make.bat uses now the command

```batchfile
fasmg.exe *
```
and not
```batchfile
start /min /wait fasmg.exe
```
so the exact "screenshot" had to be
```
=== Building Windows BMI2 Executable ===
flat assembler g  version *
The system cannot find the file specified.
```
# )

@Counterply, a way of being SURE we are in the required folder is:
```batchfile
@echo off

echo This make.bat SHOULD run without administrator privileges. If you have ran it as admin close and double click the file to reopen it without admin privileges.
pause>nul

call currDir

:currDir
pushd %cd%
goto:eof
```
so now, after or before every build a
```batchfile
popd
```
command ensures that we are in the starting folder

@double-beep

**Comment by Sportsmen** [comment]
I downloaded the latest asm to take some screen shots, to show why it was not working.... and it works....
Great job guys, way to fix it! 🥇 
![unzip](https://user-images.githubusercontent.com/24534158/43411377-9c52a882-93ef-11e8-9f37-cd2fa8a1a00c.jpg)
![works](https://user-images.githubusercontent.com/24534158/43411381-9ebb3f8a-93ef-11e8-9c66-dc6dbe753e03.jpg)
