### ISSUE TITLE
Question: does project is dead?

### ISSUE THREAD

**Issue by d3vv** [lantonov/asmFish#217]
subj

**Comment by double-beep** [comment]
@d3vv please refer to issue #174
https://github.com/lantonov/asmFish/issues/174#issuecomment-430811374 and
https://github.com/lantonov/asmFish/issues/174#issuecomment-419310310
and close the issue.

**Comment by CounterPly** [comment]
Since this appears to be a common concern, I have provided a general update here: https://github.com/lantonov/asmFish/issues/218
