### ISSUE TITLE
Latest asmFish versions and progress update

### ISSUE THREAD

**Issue by CounterPly** [lantonov/asmFish#218]
To clarify some recent points of confusion and concern:

- No, asmFish is not dead. 

- This repository (asmFish/lantonov) is currently stalled at [this patch](https://github.com/official-stockfish/Stockfish/commit/91a76331ca27b40d63f0031fbd7b9e41ead354d4), from the month of May. This patch is particularly challenging due to the "cuckoo table" initialization portion of the "upcoming repititions" patch, but it is still being worked on and is nearing completion

- To compensate for this temporary stall in progress, I have continued adding patches at my fork located at https://github.com/CounterPly/asmFish. The patches located there are correct, and the benches are matched against a recompiled version of SF (minus the "upcoming reptitions" patch, of course).

- Currently, my fork contains: **(1)** the rest of the functional patches from the month of May, **(2)** all of the functional patches from the month of June, and **(3)** functional patches through late July. At the moment, the version of asmFish located on my fork (asmFishCP) is noticeably stronger than the official version of asmFish located here (asmFish/lantonov).

- For those that are only interested in the latest stable executables, all builds are available for highspeed download [here](https://counterply.com/asmfishcp). They are also available for individual download at the repository itself.

- Once the "Upcoming Reptitions" patch is ported and "official" progress is resumed, I will incrementally migrate over all patches from my fork to asmFish/lantonov. At that time, I will add any necessary optimizations and complete all corresponding ARM ports.

- For additional details petaining to recent patches, please refer to the patches/notes/readMe located at [the asmFishCP branch](https://github.com/CounterPly/asmFish/tree/asmFish-CounterPly).

**Comment by mausalimi** [comment]
got it, thanks.

**Comment by d3vv** [comment]
@CounterPly 
Could it possible to tell us more about Medulla against short description on site?

**Comment by CounterPly** [comment]
@d3vv Absolutely. The other parts of the site are still a work in progress, but I am glad you've already started exploring. I'll be able to add in additional descriptions over the weekend.

**Comment by d3vv** [comment]
@CounterPly I have some questions.. ))
What about Medulla description? What is a difference from Cerebellum?
Why not to use xoshiro random into asmfish against old xorshift if it faster and has more quality?
Could it possible to commit asmFishCP binaries more often(with each applied patch) for testing?

**Comment by CounterPly** [comment]
@d3vv

I am a fan of Thomas Zipproth's efforts with Cerebellum, but there are several key differences between the two projects. Cerrebellum is a graph derived entirely from Stockfish, whereas Medulla derives lines from a variety of different sources including corresponence databases and high-quality engine games. Additionally, min-maxing and back-propogation of computed values in Medulla is performed selectively (rather than universally) as a function of line frequency using the latest versions of asmFishCP located at my fork.

I posted the Medulla description to the site a while ago, but if you need further information I would reccommend the book's [thread](http://mzchessforum.altervista.org/viewtopic.php?p=31381#p) at MZ Chess Forum.

Feel free to ask any further questions there, but it is better to keep discussion here related to asmfish.

As for your other question/suggestion, I will look into it when I have time since @tthsqe12 likely made that decision. If you could refer to the specific sections of the source that you are referring to, it would be helpful.

**Comment by d3vv** [comment]
@CounterPly Thank you for feedback

As for PRNG sources, I mean:

http://xoshiro.di.unimi.it/

And as for me, when I need ultra fast non-crypto prng, I prefer:

http://xoshiro.di.unimi.it/xoshiro256plus.c

And for zobrist-hashing too, despite the fact that it is recommended for floating-point numbers by Sebastiano Vigna (an author of original xorshift64 algo which is used into stock/asmfish).

**Comment by d3vv** [comment]
just offtopic reminder about Medulla:

http://mzchessforum.altervista.org/viewtopic.php?f=74&t=4312&p=38733#p38733

**Comment by lantonov** [comment]
Thanks, Justin, for the wonderful work. I still don't have the time and energy for this project but am ready to give any help you ask concerning delegating rights to this site or whatever.

**Comment by CounterPly** [comment]
Hi Lyudmil,


It is great to hear from you. No worries, regarding the absence -- I completely understand. I've been very busy myself lately as well and haven't had nearly as much time as I would like for asmFish and other projects.

In any case, here are a few updates:

**asmFish.** At the moment, asmFish on [my fork](https://www.github.com/CounterPly/asmFish) is caught up through mid October 2018 and I will be optimizing/moving over additional patches to this repository soon. Glancing ahead, the patches between now and the SF 10 benchmark don't seem too difficult, so I'll definitely be able to add those once I find time. 

**7-man Syzygy Tablebase Support.** At some point, I will also have to go back and try to add 7-man syzygy support using some instructions/tips @tthsqe12 sent me a while ago. Honestly, that has been on my to-do list for quite a while, but I just haven't had the time. Maybe we'll get lucky and Moha will add them in himself before I get to it, but I know he's likely busy as well these days with other cool projects.

**armFish.** As noted elsewhere, armFish is still stuck at the upcoming repetitions (cuckoo) patch since I could not get the benches to align there for some reason. I'm probably just missing something trivial, but it is very time-consuming to figure that out. For now I've decided to at least try to use what little spare time I have to keep progress going with x86 asmFish. Besides, I'm pretty confident that I could get the rest of armFish caught up in a matter of a couple days once the upcoming repetitions patch is added.

**Repository banner.** With regards to site rights, the only real thing I can think of at the moment is that the repo description often lags many months behind the latest update, which may cause confusion for some. As far as I know, I can't edit it myself, so moving forward the best course of action may be to make the description/banner of the respository date-neutral, but I'm open to any other suggestions you may have.
