### ISSUE TITLE
Update: Commit migration in progress.

### ISSUE THREAD

**Issue by CounterPly** [lantonov/asmFish#221]
Over the next few days, patches will be optimized and migrated over from [CounterPly/asmFish](https://github.com/CounterPly/asmFish) to this repository. 

Please note that armFish progress is on pause until the benches are properly aligned for [this patch](https://github.com/lantonov/asmFish/commit/8da6f9133904e75f05997bff8708b32412bfb8a2).

Thank you to everyone who helped with testing/trouble-shooting these patches as well as to everyone else for remaining patient through this period of slow progress. After the migration is finished, asmFish (x86) will correspond to SF from Fall of 2018 with many more patches from 2018/2019 coming soon.

**Comment by double-beep** [comment]
What is the progress for ARMfish?

**Comment by CounterPly** [comment]
Hi double-beep. As mentioned above, there is still no progress on ARM. I've invested a lot of time trying to implement the "upcoming repetitions" patch as done in x86-asm, but I have not had any success on this front. Part of the issue is that I am not able to debug in ARM as I do in x86, so it's a bit hard for me to isolate where exactly things are going wrong. Hopefully, @tthsqe12 would be able to take a look whenever he has the time.
