### ISSUE TITLE
Syzygy 7men support

### ISSUE THREAD

**Issue by ik4u** [lantonov/asmFish#225]
Kindly add support for 7 men syzygy tablebase

**Comment by CounterPly** [comment]
Thanks for posting this. Please refer to https://github.com/lantonov/asmFish/issues/218#issuecomment-490796754 for a general update on this feature.

**Comment by CounterPly** [comment]
Closed due to inactivity. While I'd still like to do this one day for fun, it is very unlikely to be of use to anyone, especially as recent tests with the latest SF versions suggest that TB lookups are do not provide as much ELO boost as they once did.
