### ISSUE TITLE
How is asmFish doing these days?

### ISSUE THREAD

**Issue by tthsqe12** [lantonov/asmFish#230]
Hello! It has been a long time and I almost forgot that this repo still exists. Some questions/comments:
1. At last update, how was the speed generally as compared with official stockfish compiled with gcc?
2. I see that official stockfish now has lots of asm in it already? and it ships with a 40MB black box included in the executable?
3. There is now a [calm-powered fasmg](https://board.flatassembler.net/topic.php?t=21324) available which is a lot of fun and should reduce build times.

**Comment by tthsqe12** [comment]
Ok. Let's let it rest in peace. I hope all of the contributors had fun. Are any of you all working on asm-related projects?
Indeed, Stockfish's strength is in the stratosphere now, and I see Komodo is not far behind in incorporating these changes. And, it is good to see that Houdini got shown for its true colors.

**Comment by CounterPly** [comment]
@tthsqe12 Great to hear from you. At its peak, asmFish 10 was faster than GCC 7 by around 16%. I haven't benchmarked asmFish in years though. It would be interesting to see how the speed of Stockfish 10 (compiled with the latest GCC) compares to the speed of asmFish 10. 

Couldn't agree more that this project was a lot of fun; I really enjoyed working on it and thoroughly enjoyed seeing all of the clever optimizations you were able to come up with. If you ever decide to start working on any asm-related project again (chess-related or not) please let me know. I may not have time to contribute a whole lot these days, but you will always have a fan in me.

**Comment by Ipmanchess** [comment]
Nice to hear something from you! To know that AsmFish each time when updated till last patch i had it around +20Elo higher then Stockfish in my testings and lists!
A pitty not more people could maintain and update the source each time ,which was a hugh task..
There are more programmers who came back after 10years ,so you never know..i'm 43years into computer chess and still testing engines non-stop on 3 systems.

Kind regards,
Ipman.

**Comment by tthsqe12** [comment]
@CounterPly Thanks for the kind words. Unfortunately, I don't think my asm-related projects can be realized at this stage. However, I have just started to write them up on my github.io page, where you will have to navigate to find the castle.
