### ISSUE TITLE
Please review new patch

### ISSUE THREAD

**Issue by lantonov** [lantonov/asmFish#25]
During the weekend, I applied the latest SF patch Simplify TT penalty stat (#980) which consisted of only deleting 2 lines (SearchMacros.asm:1653-54) involving the condition on alpha. Bench corresponds (5941174).
@muxel, @tthsqe12, please review if this is correct and sufficient.

**Comment by tthsqe12** [comment]
yes, correct.

**Comment by lantonov** [comment]
Thanks, closing.
