### ISSUE TITLE
-m 50000

### ISSUE THREAD

**Issue by lantonov** [lantonov/asmFish#26]
From the manual:
"In the command line you can also include -m option followed by a number, which specifies how many kilobytes of memory flat assembler should maximally use. In case of DOS version this options limits only the usage of extended memory."
Why is this memory limitations on our compiles? Is it possible for it to affect engine strength ?

**Comment by tthsqe12** [comment]
memory limitation doesn't affect the generated code, only the assembler's ability to generate code. It is good to have a limit because you never know if you might have made some exploding macro. It would be better for the assembler to run out of memory than take all of it.

**Comment by lantonov** [comment]
Thanks for the answer. So it's good to leave it as is.
