### ISSUE TITLE
How about an armFish?

### ISSUE THREAD

**Issue by tthsqe12** [lantonov/asmFish#31]
It might be interesting to see what can be done on aarch64. One can almost translate the base version of asmFish directly to aarch64. However, there are 16 additional gpr's! I will be using fasmarm (https://arm.flatassembler.net/) to accomplish this and testing with qemu-aarch64 on unbuntu.

**Comment by lantonov** [comment]
Sure, why not if it isn't a big trouble. Will you make it on the master branch with separate flag or will you put it on a separate branch. If the latter, I can help you to create and manage that branch.

**Comment by tthsqe12** [comment]
so it should be in asmFish/armFish and then guts for example would be in asmFish/armFish/guts

**Comment by lantonov** [comment]
If it is different branch, it can have its own set of directories which may be or not be the same as for asmFish.
I will make now an armFish branch in my repository which you can clone and change how you like it.
If you use a command line git the command for creating a new local branch is:
`git checkout -b armFish`
The command to import the content of armFish branch from remote is (you are in local branch armFish):
`git pull upstream armFish`
After that you push the local branch armFish and simultaneously create remote armFish in your repository with:
`git push --set-upstream origin armFish `

Ok, now you will find a branch armFish in https://github.com/lantonov/asmFish/tree/armFish which is the same as master but you can change it later.
If you don't have a command line git or cannot manage, I can create armFish branch in your repository with a pull request.

**Comment by tthsqe12** [comment]
I don't think a branch is appropriate for the arm code. It is not a 'parallel version' in the sense that it will exist along side of the x64 version waiting to be merged. What I was talking about was simply adding a new directory called armFish to the master branch. This directory will hold all of the stuff related to arm architecture. The make files could also be updated to make both x64 and aarch64 executables once the assembler fasmarm is ready.

**Comment by lantonov** [comment]
Parallel branches can also be updated simultaneously but I see your point. You would like to make armFish like asmFish and pedantFish to be assembled with one make command. 
Creating a directory within master branch is easy. Directly in your repository with the button "Create new file", you create asmFish/armFish/ReadMe.txt (you must have at least 1 file in a directory).
If you want to delete the created armFish branch:
Locally `git branch -d armFish`
In the remote repository `git push origin --delete armFish`
I made armFish directory in master so you can just pull it.
