### ISSUE TITLE
messy commit on 3/9/2017

### ISSUE THREAD

**Issue by tthsqe12** [lantonov/asmFish#34]
So I downloaded my fork to my windows box and made some (small) changes. I then uploaded the changed files via the online interface. Unfortunately, the diff checker seems to think that the whole file was changed, but only a small portion of each file changed.
Could it be the line endings?

**Comment by lantonov** [comment]
I will try to pull it as usual (fetch+merge) and it should find only the differences. Let's see.

**Comment by lantonov** [comment]
It just copied the patch as is -- the whole files. I'll try several more tricks to make it show only changes.

**Comment by lantonov** [comment]
I made in my repository a correct patch that shows only changes. The cleanest way to proceed is:
1. remove the last patch in https://github.com/tthsqe12/asmFish with commands:
`git reset --hard HEAD~1` (removes the last patch in your local drive)
`git push origin +master`  (remove the last patch in remote -- https://github.com/tthsqe12/asmFish)
The + in the second command is important to force removal
2. Pull the patch that I made in https://github.com/lantonov/asmFish with the command:
`git pull upstream master`
3. Push the patch in your fork with the command:
`git push origin master`
In this way you will get a clean, non-branched master.
If you can't manage this, write here again and I will start a pull request.

**Comment by lantonov** [comment]
Another possibility is for me to force push the last commit in your fork but this can have unforseeable consequences. Better proceed as above, if you can.

**Comment by lantonov** [comment]
In all cases it is helpful to look in https://github.com/tthsqe12/asmFish/network to decide what to do next.

**Comment by lantonov** [comment]
Good, you deleted it. Now just have to pull.

**Comment by lantonov** [comment]
Perfect!

**Comment by tthsqe12** [comment]
so I got everything to work. I had always used a linux box to commit/upload files and didn't expect the windows box to make such a mess. Do you know what the exact issue was?
This is a nice patch speed-wise and it is nice to see the differences.

**Comment by lantonov** [comment]
I suppose it were indeed the file ends. There should be a lone file-end character in the last line of each file.

**Comment by lantonov** [comment]
If it was transferred from Linux, the file ends are UNIX-like and are different from Windows.
