### ISSUE TITLE
another possible messy commit incoming 

### ISSUE THREAD

**Issue by tthsqe12** [lantonov/asmFish#35]
I have another +0.4% speed increase. However, I'm giving this warning since it is on windows box.

**Comment by tthsqe12** [comment]
BTW, I use build tester on windows for speed comparisons because I have not found linux+fishbench to be reliable.

**Comment by lantonov** [comment]
The patch looks good to me as it shows the differences.
Build tester is fine. Mike Babagian consulted me for ANOVA and comparisons are statistically sound. Also, he took measures to mitigate as much as possible the variability coming from other processes.
