### ISSUE TITLE
Patches in SF 15-25 March 2017

### ISSUE THREAD

**Issue by lantonov** [lantonov/asmFish#37]
There have been 5 patches in SF for 15-19 March 2017:

- Skip quiet moves based on moveCount pruning threshold and history stats
- History stat bonus: Move condition to bonus calculation 
- Pawns count imbalance table  
- Assorted code style fixes
- Fix pawn entry prefetch

Two of these change bench (functional) and I guess those are obligatory:
- **Skip quiet moves based on moveCount pruning threshold and history stats**
- **Pawns count imbalance table**

I am almost sure that the following patch does not need to be included:
- Assorted code style fixes

I am not sure about the remaining two patches:
- History stat bonus: Move condition to bonus calculation
- Fix pawn entry prefetch

"History stat bonus: Move condition to bonus calculation" claims 0.5% speed increase. "Fix pawn entry prefetch" shows minimal speed increase on some machines.

**Comment by 0zymandia2** [comment]
Two more patches from March 25th:

- Simplify ThreatBySafePawn scoring 

- Singular extension and check extension tweak

Both had positive results in benching.

**Comment by lantonov** [comment]
For "Pawns count imbalance table", I don't understand the following piece of code:
```
// PawnsSet[count] contains a bonus/malus indexed by number of pawns
const int PawnsSet[9] = { 
     24, -32, 107, -51, 117, -9, -126, -21, 31
  };
```
Shouldn't it be `PawnsSet[]` ?

**Comment by lantonov** [comment]
Thanks, Moha!!!
