### ISSUE TITLE
Weird score in multi-PV

### ISSUE THREAD

**Issue by mbabigian** [lantonov/asmFish#39]
I was analyzing r1b1kbnr/1pqp1ppp/p1n1p3/8/3NP3/2N1B3/PPP2PPP/R2QKB1R w KQkq - 0 7 using the popcnt version March 28th, 2017 build in multi-pv=2.  I was using 6 threads and 8192 MB hash, Large Pages, in the Fritz 14 GUI.  The program had access to the 5 piece Syzygy files.

At about 30 or 31 ply (sorry I wasn't paying close attention), it showed Qf3 as best with a reasonable score and a3 as second best.  The a3 move was scored as #1 (mate in one).  Since a mate in one is impossible, it caught my eye. The erroneous score eventually disappeared and was replace with a plausible score.

Not sure if this is reproducible, but I thought I'd forward it along.

**Comment by lantonov** [comment]
This issue seems to be connected to (or the same as) issues #38 and #40

**Comment by lantonov** [comment]
This is the same as official-stockfish/Stockfish#502
I couldn't reproduce it until ply 36 at the same condition. According to Joerg Oster this problem happens when search is interrupted.

**Comment by mbabigian** [comment]
Thanks for the reply and details.  In my case I didn't interrupt the search, but instead was just watching the top two lines as the search progressed.  The score appeared and within less than one minute was replaced with a reasonable score.  Hopefully someone will eventually construct a fix for the issue.  I was originally concerned the search was bugged, but if it is just a display issue that isn't a big deal.

**Comment by lantonov** [comment]
It is also in SF and irreproducible / spontaneous so closing

**Comment by lantonov** [comment]
See PR [#502](https://github.com/official-stockfish/Stockfish/pull/1074)
