### ISSUE TITLE
Strange mate score of asmFishW_2017-03-28_popcnt.exe

### ISSUE THREAD

**Issue by fsmosca** [lantonov/asmFish#40]
`info depth 16 seldepth 26 multipv 3 time 6873 nps 1239588 score mate -2147483647 nodes 8519690 tbhits 0 hashfull 267 pv b2b4`

**score mate -2147483647**

> setoption name Hash value 256
> setoption name Threads value 1
> setoption name MultiPV value 5
> isready
> info string hash set to 256 MB no large pages
> readyok
> ucinewgame
> position fen r1bqr1k1/pp3ppp/1bpp1nn1/4p3/3PP3/2PB1N1P/PP1N1PP1/R1BQR1K1 w - - 0 12
> go infinite
> 
> [...]

**Comment by lantonov** [comment]
Final fix for this issue is in commit c63d79c and executables of 2017-03-30

**Comment by fsmosca** [comment]
I have not seen such strange mate score from some tests.
