### ISSUE TITLE
asmFishW_04_03 having issues with Syzygy again

### ISSUE THREAD

**Issue by pjdouillard** [lantonov/asmFish#45]
Just wanted to let you know about this problem that should have been fixed around last 14th of February where asmFish isn't able to win and just plays move around uselessly even though eval is at +128 for it.

Look around move 52 for the problem to start.

[asmFish_issue_with_EGTB.pgn.txt](https://github.com/lantonov/asmFish/files/907787/asmFish_issue_with_EGTB.pgn.txt)

**Comment by pjdouillard** [comment]
[asmFish_issue_with_EGTB.pgn.txt](https://github.com/lantonov/asmFish/files/907786/asmFish_issue_with_EGTB.pgn.txt)

**Comment by lantonov** [comment]
I loaded the game in winboard and continued it fro move 82 when the eval was a sure win for white. Played asmfish vs asmfish with syzygy.

[Event "Computer Chess Game"]
[Site "DESKTOP-RL8DOC5"]
[Date "2017.04.08"]
[Round "-"]
[White "asmFishW_2017-04-08_bmi2"]
[Black "asmFishW_2017-04-08_bmi2"]
[Result "1-0"]
[TimeControl "120+10"]
[Annotator "83. +128.47   82... -98.72"]

1. e4
{[%eval 0,0] [%emt 0:00:00]}
1... e5
{[%eval 0,0] [%emt 0:00:00]}
2. Nf3
{
[%eval 0,0] [%emt 0:00:00]}
2... Nc6
{[%eval 0,0] [%emt 0:00:00]}
3. Bc4
{[%eval 0,
0] [%emt 0:00:00]}
3... Nf6
{[%eval 0,0] [%emt 0:00:00]}
4. d3
{[%eval 0,0] [%emt 0:
00:00]}
4... Bc5
{[%eval 0,0] [%emt 0:00:00]}
5. c3
{[%eval 0,0] [%emt 0:00:00]}
5... d6
{[%eval 0,0] [%emt 0:00:00]}
6. O-O
{[%eval 0,0] [%emt 0:00:00]}
6... a5
{[%eval 0,
0] [%emt 0:00:00]}
7. Bg5
{[%eval 0,0] [%emt 0:00:00]}
7... Ba7
{[%eval 0,0] [%emt
0:00:00]}
8. Nbd2
{[%eval 0,0] [%emt 0:00:00]}
8... h6
{[%eval 0,0] [%emt 0:00:00]}
9. Bh4
{[%eval 0,0] [%emt 0:00:00]}
9... g5
{[%eval 0,0] [%emt 0:00:00]}
10. Bg3
{
[%eval 0,0] [%emt 0:00:00]}
10... O-O
{[%eval 0,0] [%emt 0:00:00]}
11. Bb3
{[%eval 0,
0] [%emt 0:00:00]}
11... Be6
{[%eval 0,0] [%emt 0:00:00]}
12. a4
{[%eval 0,0] [%emt
0:00:00]}
12... Qe7
{[%eval 0,0] [%emt 0:00:00]}
13. Nc4
{[%eval 0,0] [%emt 0:00:00]}
13... Kh7
{[%eval 0,0] [%emt 0:00:00]}
14. Ne3
{[%eval 0,0] [%emt 0:00:00]}
14... Nh5
{
[%eval 0,0] [%emt 0:00:00]}
15. Nd5
{[%eval 0,0] [%emt 0:00:00]}
15... Qd8
{[%eval 0,
0] [%emt 0:00:00]}
16. Kh1
{[%eval 0,0] [%emt 0:00:00]}
16... Ng7
{[%eval 0,0] [%emt
0:00:00]}
17. d4
{[%eval 0,0] [%emt 0:00:00]}
17... exd4
{[%eval 0,0] [%emt 0:00:00]}
18. Nxd4
{[%eval 0,0] [%emt 0:00:00]}
18... Bxd4
{[%eval 0,0] [%emt 0:00:00]}
19. cxd4
{[%eval 0,0] [%emt 0:00:00]}
19... f5
{[%eval 0,0] [%emt 0:00:00]}
20. f3
{
[%eval 0,0] [%emt 0:00:00]}
20... fxe4
{[%eval 0,0] [%emt 0:00:00]}
21. fxe4
{
[%eval 0,0] [%emt 0:00:00]}
21... Rxf1+
{[%eval 0,0] [%emt 0:00:00]}
22. Qxf1
{
[%eval 0,0] [%emt 0:00:00]}
22... Nxd4
{[%eval 0,0] [%emt 0:00:00]}
23. Ba2
{[%eval
0,0] [%emt 0:00:00]}
23... Nc6
{[%eval 0,0] [%emt 0:00:00]}
24. Rd1
{[%eval 0,0] 
[%emt 0:00:00]}
24... Bxd5
{[%eval 0,0] [%emt 0:00:00]}
25. Bxd5
{[%eval 0,0] [%emt
0:00:00]}
25... Qe8
{[%eval 0,0] [%emt 0:00:00]}
26. Qc4
{[%eval 0,0] [%emt 0:00:00]}
26... Nh5
{[%eval 75,33] [%emt 0:01:22]}
27. Rf1
{[%eval 0,0] [%emt 0:00:00] (Le1)}
27... Nxg3+
{[%eval 78,35] [%emt 0:00:39]}
28. hxg3
{[%eval 0,0] [%emt 0:00:00]}
28... Kh8
{[%eval 44,33] [%emt 0:00:25]}
29. Bxc6
{[%eval 0,0] [%emt 0:00:00]}
29... bxc6
{
[%eval 59,30] [%emt 0:00:09]}
30. Rf7
{[%eval 0,0] [%emt 0:00:00]}
30... Rb8
{
[%eval 101,34] [%emt 0:00:51]}
31. Kg1
{[%eval 0,0] [%emt 0:00:00] (Dc3+)}
31... Rxb2
{[%eval 95,38] [%emt 0:00:36]}
32. Qc3+
{[%eval 0,0] [%emt 0:00:00]}
32... Qe5
{
[%eval 79,34] [%emt 0:00:10]}
33. Qf3
{[%eval 0,0] [%emt 0:00:00]}
33... Rb8
{
[%eval 72,37] [%emt 0:00:17]}
34. Rxc7
{[%eval 0,0] [%emt 0:00:00]}
34... Rg8
{
[%eval 70,37] [%emt 0:00:06]}
35. Qh5
{[%eval 0,0] [%emt 0:00:00]}
35... Qf6
{
[%eval 62,36] [%emt 0:00:48]}
36. Rxc6
{[%eval 0,0] [%emt 0:00:00] (Kh2)}
36... Kh7
{
[%eval 51,34] [%emt 0:00:35]}
37. Qg4
{[%eval 0,0] [%emt 0:00:00]}
37... Re8
{
[%eval 75,34] [%emt 0:01:18]}
38. Qd7+
{[%eval 0,0] [%emt 0:00:00]}
38... Re7
{
[%eval 86,38] [%emt 0:00:43]}
39. Qd8
{[%eval 0,0] [%emt 0:00:00]}
39... Re6
{
[%eval 93,37] [%emt 0:00:05]}
40. Qxa5
{[%eval 0,0] [%emt 0:00:00]}
40... h5
{
[%eval 100,39] [%emt 0:00:25]}
41. Qd2
{[%eval 0,0] [%emt 0:00:00] (Kh2)}
41... Qe5
{
[%eval 86,29] [%emt 0:00:17]}
42. Qf2
{[%eval 0,0] [%emt 0:00:00]}
42... Re7
{
[%eval 73,32] [%emt 0:00:45]}
43. Qf3
{[%eval 0,0] [%emt 0:00:00] (De3)}
43... Kg7
{
[%eval 84,37] [%emt 0:00:37]}
44. Qd3
{[%eval 0,0] [%emt 0:00:00] (Tc4)}
44... h4
{
[%eval 98,37] [%emt 0:00:19]}
45. Rxd6
{[%eval 243,49] [%emt 0:03:13]}
45... hxg3
{
[%eval 192,49] [%emt 0:00:00]}
46. Qd4
{[%eval 354,55] [%emt 0:00:14]}
46... Kf7
{
[%eval 237,51] [%emt 0:00:17]}
47. Qxe5
{[%eval 1741,45] [%emt 0:02:14]}
47... Rxe5
{
[%eval 562,52] [%emt 0:00:00]}
48. Rd1
{[%eval 1918,27] [%emt 0:00:17]}
48... Ke6
{
[%eval 664,27] [%emt 0:00:18]}
49. Ra1
{[%eval 2497,29] [%emt 0:00:10]}
49... Ra5
{
[%eval 712,43] [%emt 0:00:52]}
50. Kf1
{[%eval 12830,44] [%emt 0:00:01]}
50... Ke5
{
[%eval 697,32] [%emt 0:00:20]}
51. Ra3
{[%eval 12831,55] [%emt 0:00:00]}
51... Kxe4
{
[%eval 664,31] [%emt 0:00:05]}
52. Rxg3
{[%eval 12834,57] [%emt 0:00:50]}
52... Kf5
{
[%eval 944,38] [%emt 0:00:05]}
53. Ra3
{[%eval 12834,70] [%emt 0:00:14]}
53... Kf6
{
[%eval 1027,37] [%emt 0:00:18]}
54. Ke2
{[%eval 12834,49] [%emt 0:00:32] (Kf2)}
54... Ke6
{[%eval 1980,37] [%emt 0:00:50]}
55. Kd3
{[%eval 12839,51] [%emt 0:00:51]}
55... Kd5
{[%eval 8756,35] [%emt 0:00:00]}
56. Kc3
{[%eval 12839,60] [%emt 0:00:14]}
56... Rc5+
{[%eval 12314,32] [%emt 0:00:03]}
57. Kd2
{[%eval 12839,48] [%emt 0:00:10]
}
57... Ra5
{[%eval 9357,32] [%emt 0:00:08]}
58. Kd3
{[%eval 12839,60] [%emt 0:00:12]
(Kc3)}
58... Kc6
{[%eval 12792,29] [%emt 0:00:06]}
59. Kc4
{[%eval 12839,57] [%emt 0:
00:42]}
59... Rc5+
{[%eval 12807,54] [%emt 0:00:00]}
60. Kd4
{[%eval 12839,59] [%emt
0:01:12] (Kb4)}
60... Rd5+
{[%eval 12806,47] [%emt 0:00:04]}
61. Kc3
{[%eval 12839,
60] [%emt 0:00:07]}
61... Rc5+
{[%eval 12807,57] [%emt 0:00:00]}
62. Kd3
{[%eval
12839,60] [%emt 0:00:12] (Kb4)}
62... Rd5+
{[%eval 12806,60] [%emt 0:00:11]}
63. Ke4
{[%eval 12839,56] [%emt 0:00:11] (Kc3)}
63... Ra5
{[%eval 12806,56] [%emt 0:00:04]}
64. Ke3
{[%eval 12839,58] [%emt 0:00:00] (Kd4)}
64... Kd5
{[%eval 12802,37] [%emt 0:
00:03]}
65. Kd3
{[%eval 12839,61] [%emt 0:00:17]}
65... Kc5
{[%eval 12804,57] [%emt
0:00:00]}
66. Ke4
{[%eval 12839,60] [%emt 0:00:07]}
66... Kd6
{[%eval 12805,55] 
[%emt 0:00:00]}
67. Kd4
{[%eval 12839,51] [%emt 0:00:03]}
67... Ke6
{[%eval 12806,58]
[%emt 0:00:00]}
68. Kc3
{[%eval 12839,52] [%emt 0:00:18]}
68... Kf5
{[%eval 12806,60]
[%emt 0:00:00]}
69. Kb4
{[%eval 12839,58] [%emt 0:00:10]}
69... Re5
{[%eval 12807,58]
[%emt 0:00:00]}
70. a5
{[%eval 12839,49] [%emt 0:00:04]}
70... Re4+
{[%eval 12808,55]
[%emt 0:00:00]}
71. Kb5
{[%eval 12839,57] [%emt 0:00:06] (Kc5)}
71... Re5+
{[%eval
12809,55] [%emt 0:00:09]}
72. Kb6
{[%eval 12839,57] [%emt 0:00:00] (Kc4)}
72... Re6+
{[%eval 12808,57] [%emt 0:00:06]}
73. Kc5
{[%eval 12839,59] [%emt 0:00:01]}
73... Re5+
{[%eval 12809,56] [%emt 0:00:00]}
74. Kd6
{[%eval 12840,46] [%emt 0:00:04]
(Kc4)}
74... Re6+
{[%eval 12810,52] [%emt 0:00:04]}
75. Kd7
{[%eval 12840,53] [%emt
0:00:00]}
75... Ra6
{[%eval 12810,53] [%emt 0:00:01]}
76. Kc7
{[%eval 12840,53] 
[%emt 0:00:06] (Kc8)}
76... Kf6
{[%eval 12811,51] [%emt 0:00:03]}
77. Kb7
{[%eval
12841,52] [%emt 0:00:00]}
77... Re6
{[%eval 12812,52] [%emt 0:00:01]}
78. a6
{
[%eval 12843,46] [%emt 0:00:09]}
78... Re7+
{[%eval 12813,55] [%emt 0:00:00]}
79. Kb6
{[%eval 12844,57] [%emt 0:00:05]}
79... Re6+
{[%eval 12814,55] [%emt 0:00:00]}
80. Kc5
{[%eval 12845,48] [%emt 0:00:01]}
80... Re5+
{[%eval 12814,54] [%emt 0:00:04]}
81. Kd4
{[%eval 12845,55] [%emt 0:00:05]}
81... Re8
{[%eval 12815,55] [%emt 0:00:00]}
82. a7
{[%eval 12846,52] [%emt 0:00:01]}
82... Ra8 {-98.72/36 53} 83. Kc5 {+128.47/34 7} Rxa7 {-128.50/42 18} 84.
Rxa7 {+128.50/103 11} Ke5 {-99.78/47 7} 85. Ra4 {+99.75/41 14} g4
{-99.80/58} 86. g3 {+99.81/42 10} Ke6 {-99.82/65} 87. Re4+ {+99.83/45 10}
Kf5 {-99.82/46 10} 88. Re7 {+99.85/49} Kg6 {-99.84/63 9} 89. Kd5
{+99.87/63 0.9} Kf6 {-99.88/89 10} 90. Rc7 {+99.89/99 0.1} Kf5
{-99.90/92 10} 91. Rc6 {+99.91/110 15} Kg5 {-99.92/113} 92. Ke5
{+99.93/127 0.7} Kh5 {-99.94/127 0.1} 93. Kf6 {+99.95/127 0.6} Kh6
{-99.96/127 0.1} 94. Rc7 {+99.97/127 0.5} Kh5 {-99.98/127 0.1} 95. Rh7#
{+99.99/127 0.2}
{Xboard adjudication: Checkmate} 1-0

**Comment by lantonov** [comment]
Closing this as not confirmed.
