### ISSUE TITLE
Remove minimum to contribution from king danger to score

### ISSUE THREAD

**Issue by lantonov** [lantonov/asmFish#47]
This patch seemed straightforward and I made it by removing 3 lines of code. The bench is the same as that of the respective patch in Stockfish. However, ssj at chatwing consistently obtains worse results with this patch than without it so began to doubt if I have done it right. 
Moha, can you look into it and correct if wrong? [1c8e117](https://github.com/lantonov/asmFish/commit/1c8e11718dc54cd931aba8a83f70bd35a5651acc) in AF and [b258b4f](https://github.com/official-stockfish/Stockfish/commit/b258b4fee789680566bff973cd6f45dc5d24b365) in SF

**Comment by lantonov** [comment]
I see that you are patching further, so I take it you approve this patch. Thanks!

**Comment by tthsqe12** [comment]
Your patch was correct of course. The rest of the patches should be ready soon.
