### ISSUE TITLE
time to get rid of asmFish/pedantFish split?

### ISSUE THREAD

**Issue by tthsqe12** [lantonov/asmFish#49]
pedant fish was created to ease the process of finding bugs in search and eval. Now that the project is relatively bug-free and piece lists have been added, there is not much need for this split. Why not just make the asmFish executables with "PEDANTIC equ 1" from now on and forget about pedantFish?
Also,
 - piece lists have a very efficient implementation, they are only slow down the move do/undo mechanics by a tiny amount (verify with perft)
 - no one can produce evidence that asmFish plays better than pedantFish
 - pedantFish is a terrible name

**Comment by lantonov** [comment]
pedantFish serves as crutches to me to see if I have applied a patch correctly (the same bench as SF). But now, as pedantFish has no longer the same bench as SF and I can ask @tthsqe12  when I am unsure, I don't see use in pedantFish. Also, it complicates things like assembly, executables, etc. So better ditch it. Maybe less people will think that asmFish and SF are the same: different benches, different evaluations, different engines. Also, trying to keep the same bench may obstruct @tthsqe12 creativity.

**Comment by lantonov** [comment]
Sorry, I couldn't grasp right away the meaning of your proposal. Basically, you want to scrap asmFish and leave pedantFish but changing its name to asmFish.
There was some discussion in TCEC chat and the prevailing opinion is in favour of this change.

**Comment by tthsqe12** [comment]
I'm glad you get the meaning now. I can assure you that I have no creativity for introducing functional changes into the engine, and my chess rating is around 1100. All of my creativity on this project goes into exactly replicating the search/eval while trying to maintain some speed.

**Comment by lantonov** [comment]
@tthsqe12, allow me to disagree. Your creativity in programming is incredibly high

**Comment by tthsqe12** [comment]
After 2600 games at 60+0.3, I have 50.14% in favor of asmFish.

**Comment by lantonov** [comment]
**ssj** 
3127 games at 60+0 (+298,=2545,-284), 50.2 %
5196 games (+476,=4218,-502), 49.7 %
5643 games (+514,=4591,-538), 49.8 %
5880 games (+535,=4783,-562), 49.8 %
6356 games (+584,=5157,-615), 49.8 %
6630 games (+608,=5385,-637), 49.8 % 
7027 games (+649,=5710,-668), 49.9 %
7324 games (+670,=5959,-695), 49.8 %
8033 games (+720,=6534,-779), 49.6 %
8828 games (+784,=7185,-859), 49.6 %
8868 games (+789,=7220,-859), 49.6 % 
+2 +/-3, LOS 95.77% for pedantFish

sterten speed measurements,
release, asmFish, pedantFish
nov04,1600950,1670038 
dec07,1610947,1705300 
jan06,1643285,1693523 
jan09,1648528,1691741 
feb06,1703122,1762447 
mar06,1701442,1766772 
mar09,1698703,1751166 
mar15,1690340,1750004 
mar28,1765704,1843293 
mar30,1769609,1827462 
apr03,1768711,1837306 
apr08,1765652,1840572 
apr09,1767336,1779872 
apr11,1779497,1840599 
apr23,1790662,1864874 
apr24,1825197,1912046 
apr26,1831961,1915894 
mar02,1829606,1898858
pedantFish is 3.59% faster with significance p < 3.852*10^(-11) by a paired t test
average for asmFishes is 1732847
average for pedantFishes is 1797321

**Comment by lantonov** [comment]
Already done with asmFish of 16 May 2017
