### ISSUE TITLE
syzygy code is still dirty

### ISSUE THREAD

**Issue by tthsqe12** [lantonov/asmFish#51]
I downloaded the last version of cfish from syzygy1's repo.
The following actions will crash cfish:
1. set syzygypath to valid location
2. set position so that search will use tbs
3. run the search
4. reset syzygypath
5. quit
As it crashes on 5, it looks like ronald was not careful about the memory management. I will see what can be done.

asmfish also would crash from the same issue (freeing a free'ed pointer) but there is a different bug preventing that.

**Comment by tthsqe12** [comment]
to replicate this in stockfish 8, in place of step 5, repeat step 4.

**Comment by lantonov** [comment]
This problem in a somewhat older Stockfish
![image](https://cloud.githubusercontent.com/assets/6498222/25515410/131657aa-2bed-11e7-962c-71f7e2a7e5ed.png)

**Comment by lantonov** [comment]
I am at work with no access to my git and will merge your fix immediately after I get home (in about 7 hours time)

**Comment by lantonov** [comment]
The bug fix is in the main repo
