### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Filebacker** [lantonov/asmFish#53]
My Avast reports a virus with asmFishW_2017-05-15_base.exe

**Comment by lantonov** [comment]
No virus in this file according to F-Secure Premium and Malware Bytes

**Comment by Filebacker** [comment]
Avast reports about a virus only with that version. Even the pedant base version is ok.
Regards,
Timo
----Alkuperäinen viesti----
Lähettäjä : notifications@github.com
Pvm : 16/05/2017 - 16:45 (UTC)
Vastaanottaja : asmFish@noreply.github.com
Kopio : ta.immonen@pp.inet.fi, author@noreply.github.com
Aihe : Re: [lantonov/asmFish] Virus (#53)
No virus in this file according to F-Secure Premium and Malware Bytes

**Comment by lantonov** [comment]
These are the only AV programs I have on this computer. Will check on another after several hours.

**Comment by lantonov** [comment]
No confirmation. Virus alert lifted.

**Comment by Filebacker** [comment]
Dear Sir,

My Avast-program is once again (last time in May) reporting about a virus with the august versions of the asmFish 

It reports about FileRepMalware

IDP.Generic.138d71940119.3.2

Best Regards,
Timo Immonen
(Filebacker)

**Comment by lantonov** [comment]
It seems that Avast labels executables below certain size as viruses. There are reports that Stockfish 32 (size below 850 kb) has been reported as virus by Avast. If there is some threshold adjustment in Avast, set it to 100 kb (asmFishes are a little above it).

**Comment by Filebacker** [comment]
Last time you did something and the problems disappeared, or did they just disappear with the new version? 
I can't find any threshold adjustment in Avast and it is very strict with the virus alarm. Unfortunately there's no way to use asmFish.
Timo
----Alkuperäinen viesti----
Lähettäjä : notifications@github.com
Pvm : 08/08/2017 - 18:35 (UTC)
Vastaanottaja : asmFish@noreply.github.com
Kopio : ta.immonen@pp.inet.fi, author@noreply.github.com
Aihe : Re: [lantonov/asmFish] Virus (#53)
It seems that Avast labels executables below certain size as viruses. There are reports that Stockfish 32 (size below 850 kb) has been reported as virus by Avast. If there is some threshold adjustment in Avast, set it to 100 kb (asmFishes are a little above it).

**Comment by lantonov** [comment]
If it's not the size, I don't know what it is. Anyway, I (who make the executables) and Mohammed Li (who actually writes the code) can guarantee that asmFish does not contain any bank hackware or ransomware. FASM.EXE (the assembler) is also virus-free as checked by several AV programs. 

As an additional precaution, maybe it's good to check the FASM.EXE used with your Avast. You can download it from the GitHub (https://github.com/lantonov/asmFish/blob/master/asmFish/FASM.EXE). If you are up to it, you can assemble asmFish on your computer and see how Avast reacts.

**Comment by Ipmanchess** [comment]
It's because last update from Avast..you have just to let Avast know it's a safe site..and you can download any asmFish without problem..it's just a false alarm!
I put the website link into Avast/Settings/General/Exclusions/url's to say it's safe.

Ipman.

**Comment by Filebacker** [comment]
That's fantastic! Thank you!
----Alkuperäinen viesti----
Lähettäjä : notifications@github.com
Pvm : 08/08/2017 - 20:03 (UTC)
Vastaanottaja : asmFish@noreply.github.com
Kopio : ta.immonen@pp.inet.fi, author@noreply.github.com
Aihe : Re: [lantonov/asmFish] Virus (#53)
It's because last update from Avast..you have just to let Avast know it's a safe site..and you can download any asmFish without problem..it's just a false alarm!
 I put the website link into Avast/settings/url's to say it's safe.
Ipman.
