### ISSUE TITLE
Neural Net

### ISSUE THREAD

**Issue by hero2017** [lantonov/asmFish#61]
I noticed neural net code is added now but is it being used? How does it work? I'm running infinite analysis and I would've thought there'd be some file created about what it learned.

There's no extra UCI options so I'm wondering if this is in preparation for the next release which will have it?

**Comment by lantonov** [comment]
Neural net file together with the other files in the 'extras' directory is an extra code that is not used in the moment. It is part of the project discussed before in issues #27 and #28. I am also itching at the fingers to try train it and see how it goes. Moha will give some instructions for use when he feels it is in a more advanced stage.

**Comment by hero2017** [comment]
Ok that's what I thought but wanted to be sure as I wasn't expecting the Neural net code added yet since last I read those threads it wasn't finished or tested yet.

Thanks for the update.
