### ISSUE TITLE
Android port tablebase issues

### ISSUE THREAD

**Issue by Nordlandia** [lantonov/asmFish#63]
Today when i was about to launch engine matches on Chess for Android, i discovered that tablebases were greyed out on asmFish. 

https://cdn.pbrd.co/images/2CzgDDKpR.png

https://cdn.pbrd.co/images/2CzK6Rtom.png

**Comment by lantonov** [comment]
asmFish or armFish ?

**Comment by tthsqe12** [comment]
of course the arm version does not have tb support yet

**Comment by Nordlandia** [comment]
How long before arm version support tb?

**Comment by lantonov** [comment]
What is your deadline ?

**Comment by Nordlandia** [comment]
There is no deadline. The best imaginable testing conditions on my Galaxy S8+ is to be armfish with tb support against Komodo 11.01. 

In the meantime i use SF 20170629.

**Comment by lantonov** [comment]
Syzygy tb support added to armFish with commit https://github.com/lantonov/asmFish/commit/12c6b1d202e3c5e0adaa81b8dfb6682dabd7f0a6
