### ISSUE TITLE
Only armFish updates?

### ISSUE THREAD

**Issue by hero2017** [lantonov/asmFish#64]
Question: Are you no longer updating asmFish with the SF patches? I don't think there's been any updates for 3 weeks or more.

**Comment by lantonov** [comment]
There was a big update yesterday of both asmFish and armFish getting even with the latest SF - https://github.com/lantonov/asmFish/wiki/Change-log

**Comment by 0zymandia2** [comment]
Yeah, your post arrived like 5 hours late, man ;-)

**Comment by hero2017** [comment]
I saw the ChangeLog but all I noticed was: 2017-06-28 arm which I assume is for arm architecture only which I believe is for Android only and not asmF for the pc.

I missed the one and only 2017-06-28 arm & asm

**Comment by lantonov** [comment]
The changes of 2017-06-27 are all asmFish. Those below:

- 2017-06-28 magics test in debug
- 2017-06-27 clean up and eliminate some uses of sbb
- 2017-06-27 Increase reduction if tt-move is a capture
         - SF 2017-06-22, bench 5725676
- 2017-06-27 Don't score as an immediate draw 2-fold repetitions of the root position
         - SF 2017-06-06, bench 6599721
- 2017-06-27 remove pedantic option, bench 6469989
