### ISSUE TITLE
make command fail on linux (latest version)

### ISSUE THREAD

**Issue by bunkbail** [lantonov/asmFish#65]
As title suggests, the make command ends prematurely at compiling matefish.

> $ make
> ./asmFish/fasm "asmFish/asmFishW_base.asm"      -m 50000 "Windows/asmFishW_2017-06-29_base.exe"
> flat assembler  version 1.71.54  (50000 kilobytes memory)
> 5 passes, 0.1 seconds, 123904 bytes.
> ./asmFish/fasm "asmFish/asmFishW_popcnt.asm"    -m 50000 "Windows/asmFishW_2017-06-29_popcnt.exe"
> flat assembler  version 1.71.54  (50000 kilobytes memory)
> 5 passes, 0.1 seconds, 116224 bytes.
> ./asmFish/fasm "asmFish/asmFishW_bmi2.asm"      -m 50000 "Windows/asmFishW_2017-06-29_bmi2.exe"
> flat assembler  version 1.71.54  (50000 kilobytes memory)
> 5 passes, 0.1 seconds, 111616 bytes.
> ./asmFish/fasm "asmFish/asmFishL_base.asm"      -m 50000 "Linux/asmFishL_2017-06-29_base"
> flat assembler  version 1.71.54  (50000 kilobytes memory)
> 4 passes, 0.1 seconds, 120722 bytes.
> ./asmFish/fasm "asmFish/asmFishL_popcnt.asm"    -m 50000 "Linux/asmFishL_2017-06-29_popcnt"
> flat assembler  version 1.71.54  (50000 kilobytes memory)
> 4 passes, 0.1 seconds, 113634 bytes.
> ./asmFish/fasm "asmFish/asmFishL_bmi2.asm"      -m 50000 "Linux/asmFishL_2017-06-29_bmi2"
> flat assembler  version 1.71.54  (50000 kilobytes memory)
> 4 passes, 0.1 seconds, 109054 bytes.
> ./asmFish/fasm "asmFish/mateFishW_base.asm"      -m 50000 "Matefinder/mateFishW_2017-06-29_base.exe"
> flat assembler  version 1.71.54  (50000 kilobytes memory)
> error: write failed.
> make: *** [makefile:9: all] Error 255

**Comment by lantonov** [comment]
Sorry, I don't have Linux and can't tell why the make command is unable to write at this point. However, I make all these versions with make.bat in Windows (including the mateFish versions for Linux) and these can be found in branch [executables](https://github.com/lantonov/asmFish/tree/executables)

**Comment by mausalimi** [comment]
i can't compile it under windows (mingw)

what exact compiler are you using @lantonov

**Comment by lantonov** [comment]
[FASM.EXE](https://github.com/lantonov/asmFish/blob/master/asmFish/FASM.EXE) assembler

**Comment by mausalimi** [comment]
sorry, of course it does work. i was posting in the wrong project. :(

btw, thanks for the good work on this!
