### ISSUE TITLE
Hash Saving Capability ..

### ISSUE THREAD

**Issue by ghost** [lantonov/asmFish#69]
This is a feature request - if possible of course.

Full post here : http://talkchess.com/forum/viewtopic.php?t=64720&postdays=0&postorder=asc&topic_view=&start=0

Daniel Jose has uci options incuded in a version of Stockfish enabling hash saving ..

'**_I added to Stockfish the capability of saving the full hash to file, to allow the user to recover a previous analysis session and continue it. It has the same added uci options than in Andscacs.
The saved hash file will be of the same size of the hash memory, so if you defined 4 GB of hash, such will be the file size. Saving and loading such big files can take some time._**'

**Comment by LouisZulli** [comment]
This feature seems to be present already, at least in the Linux version of asmFish. But it seems buggy. For one thing, the file is saved with permissions that make it unreadable, so it can only be loaded after manually changing the permissions. But, more importantly, searches using loaded hashes actually seem slower than searches of the same position starting from empty hash. Also, if I load and then _immediately_ save a TT file, the saved file differs from the one I loaded, which seems odd.

**Comment by ghost** [comment]
Ah right - apologies - should have checked first ! Long time Mac user getting to grips with Windoze.

**Comment by ghost** [comment]
Recovering the previous hash is somewhat of a mystery to me - exactly where is the saved hash file saved ? I've used hash.hsh and x.hsh with no success meaning there is/are no such files anywhere on my system. My file path was to the desktop - when I opened the file - zilch - 0kb. Help please - your parameter settings at the very least would be appreciated.

**Comment by lantonov** [comment]
You must show the path to the TTfile in the asmFish settings in order to find and load it.
`option name TTFile type string default <empty>`
in the bare program (without GUI). Where to find it in the GUI depends on the GUI

**Comment by ghost** [comment]
Thanks - back to the drawing board - let me try it again. 
Enjoy your day !!

**Comment by tthsqe12** [comment]
I just found that the ttload/ttsave functions are completely broken. Easy to fix though.

**Comment by lantonov** [comment]
The bugs in the ttload/ttsave functions were fixed by @tthsqe12 with commit 222d48c .
The executables of 05Aug contain these bug fixes

**Comment by ghost** [comment]
😀 @tthsqe12 , @lantonov !!
