### ISSUE TITLE
Insufficient resources for August 2 and August 3 versions of asmFish

### ISSUE THREAD

**Issue by 2017dennis** [lantonov/asmFish#70]
I've downloaded many previous versions of asmFish with no problem, and likewise other engines, but when I do "create new engine" in ChessBase with the last two bmi2 versions of asmFish I get an error message saying that my system has insufficient resources, and the engine file is deleted from my engines folder. It doesn't seem to be a general problem - I just now installed the latest Brainfish version without any trouble. Help!, and thanks.

**Comment by ghost** [comment]
No problems for me (i7-6820hk-win10) with creating the engine except that Chessbase says the 03aug version is really 02aug. I think maybe Chessbase has an issue ?

**Comment by lantonov** [comment]
I have no problem with i7-7500U win10. 03aug says 02aug because I assembled it shortly after midnight of 02/03 aug. 03aug contains additionally the patches committed on 02aug, see https://github.com/lantonov/asmFish/wiki/Change-log

**Comment by 2017dennis** [comment]
I have windows 10, i7-6700k, 4 cores, 4GHz, 32 GB RAM. My machine had no problem with the previous 50 or 100 or whatever versions of asmFish, and is still able to set up and run Stockfish, Komodo, Brainfish, etc. It's just the last two asmFish versions it's choking on. Any ideas?

**Comment by tthsqe12** [comment]
What is the setup of your machine?
Have you changed anything on your machine recently?
You say that previous versions installed fine - can you install a previous version now no without issues?

The only difference for windows binaries is the one fewer section in the executable because I merged the dedicated tablebase section with the data and bss sections.

**Comment by ghost** [comment]
Many thanks lantonov !

**Comment by 2017dennis** [comment]
I was able to install several older asmFish versions, just not the last two of them in their bmi2 versions. The "insufficient resources" message comes up every time. The only thing I did, I think, was to let Avira do a speed-up on my boot-up.

**Comment by 2017dennis** [comment]
@tthsqe12 Not sure what you mean by the "setup" of my machine. I gave some basic info about it just before your post; what other info would be helpful?

**Comment by lantonov** [comment]
Can you run these latest asmFishes without GUI, just double-clicking on the exe and entering `go infinite`

**Comment by 2017dennis** [comment]
Nope. If I run it from the bottom of my browser, Windows tries to stop me. I click run anyway, and then it just disappears and deletes itself from the Downloads folder. Or if I run it from the Downloads folder, then after doing "run anyway" my favorite error message comes up: "Insufficient system resources exist to complete the requested service."

**Comment by tthsqe12** [comment]
Where is the source of this "insufficient resources" message?
Is it from your gui? Is it from some other popup on windows?
You certainly have enough resources to run the program.

**Comment by tthsqe12** [comment]
Ah i see it is from windows itself. I will have to look into this message and see what mistake the windows people have made. It could be easy to fix in the source.

**Comment by 2017dennis** [comment]
It's a windows popup. The experiment I just did following lantalov's advice was done with CB closed.

**Comment by tthsqe12** [comment]
dennis, try running older asmfish's from the command line as well. it will be better to actuall open a cmd prompt and cd to the location of the exe. At that point you can type the name of the exe to run it

https://superuser.com/questions/494538/how-do-i-open-a-program-via-the-command-prompt-in-windows-8

**Comment by 2017dennis** [comment]
I did it and don't get an error message. What it is doing, I don't know, but there's no error message.

**Comment by tthsqe12** [comment]
running older version produces no error? how about the newer ones?
it should print asmfish blah blah date blah blah

you can type quite and then tap enter to quit the program

**Comment by 2017dennis** [comment]
No error on the old one; the new one gets the beloved "The system cannot execute the specified program."

**Comment by tthsqe12** [comment]
can you find the event log on your computer? there should be couple of entries from all of your beloved messages.

http://www.dummies.com/computers/operating-systems/windows-10/how-to-use-event-viewer-in-windows-10/

**Comment by 2017dennis** [comment]
The Event Viewer (Local) is open; what am I looking for (and where would it be)?

**Comment by tthsqe12** [comment]
you should probably see a list of events. You will have to look at them and see if any seem related to this issue. If you find the ones related to this issue. please post as much info as possible.

**Comment by 2017dennis** [comment]
Ah...I think Avira's antivirus program thinks the asmFish file is a virus. Now I have to figure out how to set it straight. But it never said anything that indicated this.

**Comment by 2017dennis** [comment]
Got it! It's running. Thanks, everyone, you did a great job and were very patient with me.

**Comment by tthsqe12** [comment]
Your antivirus might have a setting that is triggered when the number of sections drops below 5:
sections before: .data, .bss, .tb, .code, .idata
sections after: .data, .bss, .code, .idata

https://github.com/tthsqe12/asmFish/commit/0bffa72e276ce0b21ce89c01fe5eba47f6bf43b4#diff-7ba69d829b7cc14eb07f498750e1aca8L528
