### ISSUE TITLE
asmFish macOS - phenomenal !!

### ISSUE THREAD

**Issue by ghost** [lantonov/asmFish#71]
on my macOS Sierra 10.12.6
3.1 Ghz i7

Total time (ms) : 2702
Nodes searched  : 9060524
Nodes/second    : 3353265

Genius !!
Thank You !!

**Comment by lantonov** [comment]
Such speed on a single thread can't be reached by my i7 on win 10. Truly remarkable ! Thanks, Moha !!!

**Comment by ghost** [comment]
Bench .. asmFishX 
against Win10 i7-6820hk @2.70Ghz 
figures in brackets Nodes/second relates to Win10 
just now figured out how to copy Win10 cmd line output to clipboard

asmFishX is faster than the Win10 version on the systems mentioned above.
(Well the Mac proc is slightly faster @ 3.1Ghz)

I dont understand why the depth is at 13 for both operating systems ?


bench
*** bench hash 16 threads 1 depth 13 realtime 0 ***
===========================
Total time (ms) : 2050
Nodes searched  : 5608839
Nodes/second    : 2736019 (2257986)

bench 1024
*** bench hash 1024 threads 1 depth 13 realtime 0 ***
===========================
Total time (ms) : 2292
Nodes searched  : 5827693
Nodes/second    : 2542623 (2301616)

bench 1024 3
*** bench hash 1024 threads 3 depth 13 realtime 0 ***
===========================
Total time (ms) : 1329
Nodes searched  : 9921465
Nodes/second    : 7465361 (6337459)

bench 1024 4
*** bench hash 1024 threads 4 depth 13 realtime 0 ***
===========================
Total time (ms) : 1151
Nodes searched  : 11398003
Nodes/second    : 9902695 (8209031)


bench 2048
*** bench hash 2048 threads 1 depth 13 realtime 0 ***
===========================
Total time (ms) : 4101
Nodes searched  : 5827693
Nodes/second    : 1421041 (1996468)


bench 2048 3
*** bench hash 2048 threads 3 depth 13 realtime 0 ***
===========================
Total time (ms) : 1327
Nodes searched  : 8761282
Nodes/second    : 6602322 (6192437)


bench 2048 4
*** bench hash 2048 threads 4 depth 13 realtime 0 ***
===========================
Total time (ms) : 1222
Nodes searched  : 10840483
Nodes/second    : 8871099 (7998910)

**Comment by ghost** [comment]
I did not BOLD the bench headers .. ??

**Comment by lantonov** [comment]
In this comments editor, Bold is 2 asterisks on both sides of a word

**Comment by tthsqe12** [comment]
2.7 Mnps does seem kinda high for bench. You can test higher depths with
`bench hash 128 threads 1 depth 16`
or the abbreviated form
`bench 128 1 16`
Since a time management patch seems to be in the works for official stockfish, It might be a good time to rigorously test asmFish's _GetTime function on all three platforms. The windows implementation is the flakiest of them all because, although time differences should be calculated correctly, I haven't handled the possibility of roll over. 

One more thing: DO NOT test syzygy on mac version. I'm 99% sure the function which gets the size of a file is broken.

**Comment by maxchess** [comment]
Thanks lantonov !

Moha ..

asmFishX_2017-08-03_popcnt
uci
id name asmFishX_2017-08-03_popcnt
id author TypingALot
option name Hash type spin default 16 min 1 max 65536
option name LargePages type check default false
option name Threads type spin default 1 min 1 max 256
option name NodeAffinity type string default all
option name Priority type combo default none var none var normal var low var idle
option name TTFile type string default <empty>
option name TTSave type button
option name TTLoad type button
option name Clear Hash type button
option name Ponder type check default false
option name UCI_Chess960 type check default false
option name MultiPV type spin default 1 min 1 max 224
option name Contempt type spin default 0 min -100 max 100
option name MoveOverhead type spin default 30 min 0 max 5000
option name MinThinkTime type spin default 20 min 0 max 5000
option name SlowMover type spin default 89 min 10 max 1000
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name SyzygyProbeLimit type spin default 6 min 0 max 6
option name Syzygy50MoveRule type check default true
option name SyzygyPath type string default <empty>
uciok
**bench 128 1 16**
*** bench hash 128 threads 1 depth 16 realtime 0 ***
info string hash set to 128 MB no large pages
1:      nodes: 1045966          2216 knps
2:      nodes: 1090285          2433 knps
3:      nodes: 327440           3807 knps
4:      nodes: 603246           2693 knps
5:      nodes: 196037           2450 knps
6:      nodes: 655968           2109 knps
7:      nodes: 968378           2273 knps
8:      nodes: 2869150          2379 knps
9:      nodes: 1028203          2225 knps
10:     nodes: 276111           2533 knps
11:     nodes: 699083           2157 knps
12:     nodes: 1314587          2155 knps
13:     nodes: 786962           2115 knps
14:     nodes: 455550           2128 knps
15:     nodes: 386928           2464 knps
16:     nodes: 187107           2834 knps
17:     nodes: 235249           3136 knps
18:     nodes: 21181            3025 knps
19:     nodes: 337161           3831 knps
20:     nodes: 1131897          3482 knps
21:     nodes: 57096            4392 knps
22:     nodes: 72609            5186 knps
23:     nodes: 354816           5632 knps
24:     nodes: 245809           3367 knps
25:     nodes: 18234            3039 knps
26:     nodes: 104447           3165 knps
27:     nodes: 587054           2995 knps
28:     nodes: 483146           2808 knps
29:     nodes: 226284           2938 knps
30:     nodes: 168190           3503 knps
31:     nodes: 179852           4282 knps
32:     nodes: 203041           4143 knps
33:     nodes: 99840            4754 knps
34:     nodes: 228523           3940 knps
35:     nodes: 389672           3711 knps
36:     nodes: 109490           4562 knps
37:     nodes: 260878           3388 knps
===========================
Total time (ms) : 7133
Nodes searched  : 18405470
**Nodes/second    : 2580326**

**Comment by lantonov** [comment]
On my new laptop bench 16 1 13 is 2752129 nps
bmi2 AF on win 10 CPU i7-7500U
bench 128 1 16 is 2579603 nps

**Comment by ghost** [comment]
Thanks lantonov problem is I'm copying/pasting from command terminal output directly here. Anyway not an issue. I'll try to solve this one later.

For Moha ..

asmFishX_2017-08-03_popcnt
uci
id name asmFishX_2017-08-03_popcnt
id author TypingALot
option name Hash type spin default 16 min 1 max 65536
option name LargePages type check default false
option name Threads type spin default 1 min 1 max 256
option name NodeAffinity type string default all
option name Priority type combo default none var none var normal var low var idle
option name TTFile type string default <empty>
option name TTSave type button
option name TTLoad type button
option name Clear Hash type button
option name Ponder type check default false
option name UCI_Chess960 type check default false
option name MultiPV type spin default 1 min 1 max 224
option name Contempt type spin default 0 min -100 max 100
option name MoveOverhead type spin default 30 min 0 max 5000
option name MinThinkTime type spin default 20 min 0 max 5000
option name SlowMover type spin default 89 min 10 max 1000
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name SyzygyProbeLimit type spin default 6 min 0 max 6
option name Syzygy50MoveRule type check default true
option name SyzygyPath type string default <empty>
uciok

bench 128 1 16

*** bench hash 128 threads 1 depth 16 realtime 0 ***
info string hash set to 128 MB no large pages
1:      nodes: 1045966          2216 knps
2:      nodes: 1090285          2433 knps
3:      nodes: 327440           3807 knps
4:      nodes: 603246           2693 knps
5:      nodes: 196037           2450 knps
6:      nodes: 655968           2109 knps
7:      nodes: 968378           2273 knps
8:      nodes: 2869150          2379 knps
9:      nodes: 1028203          2225 knps
10:     nodes: 276111           2533 knps
11:     nodes: 699083           2157 knps
12:     nodes: 1314587          2155 knps
13:     nodes: 786962           2115 knps
14:     nodes: 455550           2128 knps
15:     nodes: 386928           2464 knps
16:     nodes: 187107           2834 knps
17:     nodes: 235249           3136 knps
18:     nodes: 21181            3025 knps
19:     nodes: 337161           3831 knps
20:     nodes: 1131897          3482 knps
21:     nodes: 57096            4392 knps
22:     nodes: 72609            5186 knps
23:     nodes: 354816           5632 knps
24:     nodes: 245809           3367 knps
25:     nodes: 18234            3039 knps
26:     nodes: 104447           3165 knps
27:     nodes: 587054           2995 knps
28:     nodes: 483146           2808 knps
29:     nodes: 226284           2938 knps
30:     nodes: 168190           3503 knps
31:     nodes: 179852           4282 knps
32:     nodes: 203041           4143 knps
33:     nodes: 99840            4754 knps
34:     nodes: 228523           3940 knps
35:     nodes: 389672           3711 knps
36:     nodes: 109490           4562 knps
37:     nodes: 260878           3388 knps
===========================
Total time (ms) : 7133
Nodes searched  : 18405470
Nodes/second    : 2580326

**Comment by ghost** [comment]
Lantonov : whats the laptop's config please ?

**Comment by lantonov** [comment]
as above: win 10 on CPU i7-7500U 8 GB RAM

**Comment by ghost** [comment]
Gotcha - not much of a difference then between our (Mac/W10) nodes/second.

**Comment by mausalimi** [comment]
i wonder why i get better results on my ancient i7 3770k?

asmFishW_2017-08-06_popcnt bench 128 1 16
Total time (ms) : 6066
Nodes searched  : 18405470
Nodes/second    : 3034202

asmFishW_2017-08-06_popcnt bench 128 11 16
Total time (ms) : 3499
Nodes searched  : 58886071
Nodes/second    : 16829400
^^^ wow
