### ISSUE TITLE
USE_BOOK issue

### ISSUE THREAD

**Issue by YouriAndropov** [lantonov/asmFish#72]
Hi,

I just compiled asmFish with USE_BOOK = 1, I can see the book is loaded ("info string 360125 entries in book (0 entries have zero weight)") but not used. When starting a game, asmFish thinks instead of using the book. Did I miss something ?

Thank you.

**Comment by tthsqe12** [comment]
Did you forget to set OwnBook = true?
<pre>
$ ./afish
asmFishL_2017-08-06_popcnt
uci
id name asmFishL_2017-08-06_popcnt
id author TypingALot
option name Hash type spin default 16 min 1 max 65536
option name LargePages type check default false
option name Threads type spin default 1 min 1 max 256
option name NodeAffinity type string default all
option name Priority type combo default none var none var normal var low var idle
option name TTFile type string default <empty>
option name TTSave type button
option name TTLoad type button
option name Clear Hash type button
option name Ponder type check default false
option name UCI_Chess960 type check default false
option name MultiPV type spin default 1 min 1 max 224
option name Contempt type spin default 0 min -100 max 100
option name MoveOverhead type spin default 30 min 0 max 5000
option name MinThinkTime type spin default 20 min 0 max 5000
option name SlowMover type spin default 89 min 10 max 1000
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name SyzygyProbeLimit type spin default 6 min 0 max 6
option name Syzygy50MoveRule type check default true
option name SyzygyPath type string default <empty>
option name OwnBook type check default false
option name BookFile type string default <empty>
option name BestBookMove type check default false
option name BookDepth type spin default 100 min -10 max 100
uciok
setoption name BookFile value performance.bin
info string 92954 entries in book (0 entries have zero weight)
<b>setoption name OwnBook value true</b>
go wtime 100000
info string playing book move weight 1
bestmove e2e4 ponder c7c5
<b>setoption name OwnBook value false</b>
go wtime 10000
info depth 1 seldepth 1 multipv 1 time 1 nps 20000 score cp 93 nodes 20 tbhits 0 pv e2e4
info depth 2 seldepth 2 multipv 1 time 1 nps 47000 score cp 91 nodes 47 tbhits 0 pv e2e4 b7b6
info depth 3 seldepth 3 multipv 1 time 1 nps 111000 score cp 124 nodes 111 tbhits 0 pv d2d4 d7d6 e2e4
info depth 4 seldepth 4 multipv 1 time 2 nps 129000 score cp 107 nodes 258 tbhits 0 pv d2d4 d7d6 e2e4 d6d5
info depth 5 seldepth 5 multipv 1 time 3 nps 281666 score cp 62 nodes 845 tbhits 0 pv e2e4 e7e5 d2d4 d7d6 d4e5
info depth 6 seldepth 6 multipv 1 time 6 nps 400833 score cp 13 nodes 2405 tbhits 0 pv e2e4 e7e5 d2d4 g8f6 d4e5 f6e4
info depth 7 seldepth 8 multipv 1 time 10 nps 530300 score cp 25 nodes 5303 tbhits 0 pv e2e4 e7e5 b1c3 d7d5 c3d5 g8f6 d5c3
info depth 8 seldepth 9 multipv 1 time 16 nps 540000 score cp 18 nodes 8640 tbhits 0 pv e2e4 e7e5 b1c3 d7d5 c3d5 g8f6 d5f6 d8f6 g1e2
info depth 9 seldepth 13 multipv 1 time 22 nps 822409 score cp 13 nodes 18093 tbhits 0 pv e2e4 d7d5 e4d5 d8d5 d1e2 g8f6 g1f3 b8c6 b1c3
info depth 10 seldepth 13 multipv 1 time 32 nps 1010906 score cp 64 nodes 32349 tbhits 0 pv e2e4 d7d5 e4d5 d8d5 b1c3 d5a5 d2d4 g8f6 g1f3 c8g4 d1e2
info depth 11 seldepth 15 multipv 1 time 49 nps 1048836 score cp 55 nodes 51393 tbhits 0 pv e2e4 d7d5 e4d5 d8d5 d2d4 g8f6 c2c4 d5e6 d1e2 e6e2 g1e2 e7e5 b1c3 e5d4 e2d4
info depth 12 seldepth 19 multipv 1 time 81 nps 1179370 score cp 50 nodes 95529 tbhits 0 pv e2e4 d7d5 e4d5 d8d5 g1f3 c8g4 b1c3 d5a5 f1d3 e7e5 e1g1 a5c5 d1e2
info depth 13 seldepth 20 multipv 1 time 156 nps 1330365 score cp 60 nodes 207537 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 d1e2 d8e7 c1g5 e7e2 g1e2 b8c6 b1c3 f8b4 e1c1
info depth 14 seldepth 22 multipv 1 time 326 nps 1416481 score cp 26 nodes 461773 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 b1c3 f8e7 g1f3 g8f6 f1b5 c7c6 b5d3 h7h6 h2h3 c8e6 e1g1 e8g8
bestmove e2e4 ponder e7e6
quit
$
</pre>

**Comment by YouriAndropov** [comment]
Curiously there is no 'ownbook' button in asmFish configuration panel in Arena GUI, only a bookfile FileSelector and a BestBookMove button.

Edit : I don't know why but now Arena sends a "setoption name OwnBook value true" where there is no OwnBook button in asmFish config panel. You can close the issue I presume, it was related to Arena.

**Comment by lantonov** [comment]
Winboard has the following settings for own books
![image](https://user-images.githubusercontent.com/6498222/29016494-55958c50-7b5b-11e7-84f4-1755507f9bdc.png)

![image](https://user-images.githubusercontent.com/6498222/29016384-eca1fd64-7b5a-11e7-9a7b-3a54bca97da1.png)

**Comment by YouriAndropov** [comment]
By the way, I'm doing some testing, asmFish seems very powerful and works well. Congrats ! asmFish beats Komodo 10.3 where stockfish don't.

**Comment by foxnights** [comment]
Dear, please explain more clearly to the inexperienced user in programming what and where to change to guts so that asmFish of a personal assembly uses OwnBook?

**Comment by lantonov** [comment]
In the directory https://github.com/lantonov/asmFish/tree/master/asmFish, in one of the asmFish*.asm files make `USE_BOOK equ 1`

**Comment by foxnights** [comment]
lantonov, to display the book options in the parameters - this is understandable. But asmFish now thinks at the beginning of the game, but I would like to play the book. Earlier (in the spring) it was just like that ...

**Comment by lantonov** [comment]
asmFish thinks at the beginning of the game if you have no book

**Comment by foxnights** [comment]
I can clearly demonstrate. As it happens in the program Fritz11. Using the spring engine and collected today, he thinks already on the second move. Please, just a minute, I'll make a video

**Comment by foxnights** [comment]
https://youtu.be/ZdciOZ66n-c
Two engines. The first of March 7 and the second today's assembly

**Comment by foxnights** [comment]
Maybe I did something misunderstood. Just noticeable differences from the old asmFish, why he traverses the moves, when there is a book, I'm sorry if I wasted time

**Comment by lantonov** [comment]
try `USE_BOOK equ 1` per above

**Comment by foxnights** [comment]
Thank you for your help. I'll see. For a long time did not play the engine, and visual changes are more than noticeable in the latest asmFish.

**Comment by lantonov** [comment]
I think of making USE_BOOK set by default. In the make.bat file, USE_BOOK will be off only in Matefinder. Is there any objection to this?

**Comment by tthsqe12** [comment]
Yes - there is a bug in the current book functions. It should be thinking in analysis mode (go infinite, go depth 20, ...), but it instead just spits out a book move. I will fix this on my repo and also git rid of the need for environment variables.

EDIT: no - I think this is not a bug. What do you think @lantonov ? Should the engine check the book in analysis mode (assuming the ownbook book option is set to true)?
Currently we have:
(1) in analysis mode with ownbook=true, engine will try a book move
(2) in analysis mode with ownbook=false, engine will think think and will not try a book move

I think I did it this way so that there was a way to see the book moves in analysis mode. If I go back to the other way, there is no way to see the book moves when analysing (i.e. no (1))

**Comment by lantonov** [comment]
Most GUIs (maybe all, even) have an easily available option to switch ownbook on or off. So if the user wants to analyse some book moves he easily do so just by unchecking the ownbook box.
For example, in Winboard, I have available 2 books for each engine: one is the engine's own book and the other is a GUI book which is available for all engines, even to those that do not support own book. By unchecking First has Own Book and Second has Own Book and checking Use Book in the Common Engines settings dialog like this
![image](https://user-images.githubusercontent.com/6498222/31307280-c7cd1cac-ab58-11e7-9f45-410bf25968ff.png)
I leave only the common (GUI) book. Winboard is smart enough to know that in Analysis mode it should switch off the GUI book for the engines. However, it still shows the GUI book moves in the Edit book dialog
![image](https://user-images.githubusercontent.com/6498222/31307341-7cc10a1e-ab5a-11e7-879e-6888343d5d0e.png)
In this example early in Giuoco Piano, asmFish analysis shows that 4. d3 is better than 4. O-O. The book shows the same -- d3 has 3 points (50%) while O-O has 2 points (33%). In this case I will not change the book.
Maybe the best to do in asmFish is for the book to be on in Play mode and off in Analysis mode. The GUIs that show book in Edit window will show either the GUI book or the own book. In either case the book will be read from somewhere so book moves will be shown whether the engines uses book or not.

**Comment by lantonov** [comment]
This patch should solve the issue: 
2017-11-06 forget about book upon go infinite 
7662888
