### ISSUE TITLE
armfish 32bit

### ISSUE THREAD

**Issue by stvs777** [lantonov/asmFish#74]
request:its possible for a 32bit armfish compile? tnx

**Comment by tthsqe12** [comment]
No.
This project is written for performance, and support for 32 bit processors would be a HUGE pain for very little gain. 64 bit processors are everywhere.

Try to understand the task required to rewrite everything for 32 bit - every 64 bit operation now needs to be split among two 32 bit registers. For high level code, your compiler will do this for you from your high level code, but as you might expect, performance drops considerably (4x-5x IIRC) from 64 bit versions. Now with the almost double number of live registers, consider the fact the most 32 bit processors have half as many general purpose registers as their 64 bit equivalents. This means that for all but the simplest operations, variables are going to have to be spilled to the stack all over the place.

x86:
64 bit: 16 general purpose registers
32 bit: 8 general purpose registers

arm:
64 bit: 30 general purpose registers
32 bit: 16 general purpose registers
