### ISSUE TITLE
cool engine.

### ISSUE THREAD

**Issue by Alexei1981** [lantonov/asmFish#75]
Cool engine! I'm testing armfish 2017
08 vs stockfish-060817. Time control
2 minutes + 1 second on the move.3
kernel, android 6.0.Armfish thwarts
stockfish!

**Comment by lantonov** [comment]
Thanks for the testing and appreciation !

**Comment by tthsqe12** [comment]
lantonov, before merging the "simplify syzygy code" into your repo, try giving it a test. It is not functionaly identical to the previous version because the search inside the tb is different, thus affecting the piece lists.
The original code from Ronald was bulky and messy, and his newer version is much nicer. This is the version that I will drop into armfish if you don't find any issues with teh x86 version.

**Comment by lantonov** [comment]
These are positions from study books which require extensive syzygy usage (see http://www.talkchess.com/forum/viewtopic.php?t=55414)
![image](https://user-images.githubusercontent.com/6498222/29161333-80c6a0d4-7dbe-11e7-98db-1614638f4b38.png)
The 2 versions have equal settings. The patch requires more time to reach depth 127 (1 min vs 42 sec), has somewhat greater speed (10629.0 vs 10086.7 knps) and makes more than twice tb hits (1493635 vs 611408).
![image](https://user-images.githubusercontent.com/6498222/29164469-284e7b52-7dc8-11e7-99af-5018421438e2.png)
In the second study the patch is much faster to reach depth 55 (1.23 vs 7.18 min) and its solution is different and closer to the author's (Troitzki). tb hits are only 15 in both.
![image](https://user-images.githubusercontent.com/6498222/29163167-489918ee-7dc4-11e7-9dab-3d381dddbd0f.png)
In the third study, the patch is faster to reach depth 50, tb hits 21 in both, and different solutions.
![image](https://user-images.githubusercontent.com/6498222/29164497-40957c60-7dc8-11e7-806a-41c180328610.png)
In a position with more pieces, the patch is a little faster with a little less tb hits.

**Comment by tthsqe12** [comment]
Alright. keep testing - especially in games.
With the "clean up TablebaseCore.asm a bit" patch, the executables drop by about 1KB in size:
`asmFishL_2017-08-08_bmi2: 108718 bytes`
`asmFishL_2017-08-10_bmi2: 107070 bytes`

A rough estimate for armFishL with syzygy is 130KB, so at this point the CISC doesn't beat RISC by that much in terms of code density.

**Comment by lantonov** [comment]
I am running 1000-games match between patch and old. Will run also 1000 games against the second simplification patch. Cutechess-cli with syzygy enabled.
The second simplification is an additional 1KB less.
asmfish Aug 08 vs. "simplify syzygy code" 1000 games depth 14 - no divergent evaluations
asmfish Aug 08 vs. "clean up TablebaseCore.asm a bit" 1000 games depth 14 - +193 -193 =614, no divergent evaluations
Stockfish Aug 06 vs. "clean up TablebaseCore.asm a bit" 1000 games depth 14 - +199 -199 =602, no divergent evaluations
IMO, it's better than expected so I'm merging.
P.S. Stockfish Aug 11 vs. "clean up TablebaseCore.asm a bit" 1000 games depth 14 - +202 -202 =596, no divergent evaluations
Stockfish Aug 12 vs. "clean up TablebaseCore.asm a bit" 1000 games depth 14 - no divergent evaluations
Harder and harder to find any differences 👍

**Comment by Alexei1981** [comment]
By the way here is the result of the test
armFish 2017 08 08 vs stockfish
060817.Time control 2m + 1s.Hash
16mb.3 core.Androud 6.0.Book =
8move.pgn.

armFish_2017_08_08= +91=368-41
stockfish 060817.     =+41=368-91

**Comment by lantonov** [comment]
Stockfish Aug 13 vs. "2017-08-13 x86: tidy up tb code (asm)" 20 games depth 14 -- 5 out of 10 divergent pairs. Either the changes in Stockfish or those in asmFish of Aug 13.
Stockfish Aug 13 vs. "2017-08-10 clean up TablebaseCore.asm a bit" 20 games depth 14 -- 4 out of 10 divergent pairs. So probably the changes in Stockfish Aug13 cause the divergence.
Stockfish Aug 12 vs. "2017-08-13 x86: tidy up tb code (asm)" 20 games depth 14 -- 2 out of 10 divergent pairs. The change in asmFish of Aug 13 also causes some divergence.
AF "2017-08-10 clean up TablebaseCore.asm a bit" vs AF "2017-08-13 x86: tidy up tb code (asm)" 500 games, no divergent pairs
SF Aug 12 vs SF Aug13 100 games, no divergent pairs
Again, Stockfish Aug 12 vs. AF "clean up TablebaseCore.asm a bit" 100 games depth 14 - no divergent evaluations
**Without syzygy**
Stockfish Aug 13 vs. AF "2017-08-13 x86: tidy up tb code (asm)" 100 games depth 14 -- +17 -20 =63, 16 out of 50 divergent pairs.

**Comment by tthsqe12** [comment]
Can you test different versions of the compiled c++ code that are supposedly functional identical? You are getting wild diversions, yet all of the changes were billed as non-functional.
This one smells funny to me:
https://github.com/official-stockfish/Stockfish/commit/f731bcadb7908f03c42e3d63fefe82552f09c926

so could you then the exe's right before and after this commit?

**Comment by lantonov** [comment]
I will continue tomorrow with testing different versions but it seems to me that discrepancies appeared with SF and AF from today (13 Aug). The tests 12 Aug and before didn't find differences in thousands of games. The strange thing is that testing AF vs AF and SF vs SF (different versions) doesn't find differences.

**Comment by tthsqe12** [comment]
where you tested AF aug 13, could you post a game where the different move is as early in the game as possible? Of course syzygy tb's should be off.
