### ISSUE TITLE
Problem with the work of the polybook.bin in the base versions.

### ISSUE THREAD

**Issue by foxnights** [lantonov/asmFish#8]
The book itself is beautifully occurs providing you instructions, but, alas, neither  nor pedantFishW base asmFishW base when this option is enabled in the settings of the uci is absolutely not use own book in the gui (fritz11 and arena 3.5.1), whereas in Komodo 10.1 64-bit , Stockfish 8 64 polybook.bin instantly responds to retaliatory moves. Is it possible to fix this?

**Comment by lantonov** [comment]
Sorry, I can't understand what is the problem. Neither fritz nor arena use .bin book (fritz uses the chessbase .ctg book and arena uses .abk book)

**Comment by foxnights** [comment]
I understand that these programs work with their formats of books (.ctg. abk) and they are connected as master books. The problem is that the engines themselves pedantFishW base asmFishW base with book polybook.bin does not perceive it as their own when connecting via options. 

![ashampoo_snap_2016 12 15_11h51m13s_001_](https://cloud.githubusercontent.com/assets/24514672/21217490/7de04d0a-c2bd-11e6-996e-9c9c1d5cffc8.png)

I.e., the book as there is, but you cannot use it. And again, Komodo 10.1 64-bit for Stockfish, 8 64 perfectly its read connected to them through the same options.

**Comment by lantonov** [comment]
Does this problem occur with the other versions of asmFish and pedantFish (bmi2 and popcnt) ? I don't have an access to 64 bit computer at the moment.
Also: Can pedantFishW base and asmFishW base use own .bin books other than polybook.bin ?

**Comment by foxnights** [comment]
Unfortunately I can't test versions asmFish and pedantFish (bmi2 and POPCNT) because my CPU doesn't support these instructions.
Other books in the same way the .bin unavailable to read the  asmFishW base  pedantFishW base engines, tested in this example ph-book2010-stockfish3.bin (Komodo 10.1 64-bit Stockfish, 8 64 and here beautifully played). The problem is definitely in the engines themselves

**Comment by lantonov** [comment]
Ok, I shall look into this when I get together with my 64 bit

**Comment by foxnights** [comment]
Thank you.
This Engine source SF_8 which polybook.bin works correctly, perhaps it kind of simplifies the task.
[SF_8.zip](https://github.com/lantonov/asmFish/files/654887/SF_8.zip)

**Comment by muxel** [comment]
asmFish prints option name "BookPath" but scans for "BookFile".
You can fix this in asmFish.asm by changing BookPath to Bookfile.

**Comment by muxel** [comment]
asmFish prints option name "BookPath" but scans for "BookFile".
You can fix this in asmFish.asm by changing BookPath to Bookfile. Case is ignored.

**Comment by muxel** [comment]
asmFish prints option name "BookPath" but expects option name "BookFile".
You can fix this in asmFish.asm by changing BookPath to Bookfile. Case is ignored.

**Comment by lantonov** [comment]
I tried Winboard and it does not have this problem. The corresponding checkbox for own book is called BookFile in Winboard. 
I changed "BookPath" to "BookFile" in asmFish.asm. The option USE_BOOK was set to 1 in asmFish base and pedantFish base while it was set to 0 in the other files. I set it to 0 in asmFish base and left it 1 in pedantFish base. Pushed the patch to master and made new executables with date 2016-12-15.
Try both asmFish base and pedantFish base to see if that fixes the problem.

**Comment by foxnights** [comment]
About the miracle, now both versions base great work with his own book. Apparently the reason was hidden exactly in an unfortunate typographical error Book**File**-Book**Path**.
Thanks a lot for the hint muxel!
lantonov for efficient solution of the underlying problem.
P.S. I do not want to seem intrusive, but maybe we should add to the perfection of the engine with a book option **Best Book Move**, which takes place in most of the best engines.
And what asmFish the very first of them is confirmed in practice

**Comment by lantonov** [comment]
The option "best book move" is typically provided by the GUI, not by the engine. For example, Winboard / Xboard have a menu item "Hint" which, when clicked shows the best book move of **the book loaded in GUI**. Generally speaking, the book is a responsibility of GUI and though many engines (including asmFish, SF, Komodo, etc.) have an option "own book", the preferred method is for the book to be loaded in GUI.
