### ISSUE TITLE
Linux Huge Pages

### ISSUE THREAD

**Issue by ChristophHeilmann** [lantonov/asmFish#80]
Can asmfish allocate huge pages? When I use the grub command line:

GRUB_CMDLINE_LINUX_DEFAULT="transparent_hugepage=never hugepagesz=1GB hugepages=128 default_hugepagesz=1GB"

and start asmfish with large pages enabled I get

root@:~# cat /sys/devices/system/node/node*/meminfo | fgrep Huge
Node 0 AnonHugePages:         0 kB
Node 0 ShmemHugePages:        0 kB
Node 0 HugePages_Total:   64
Node 0 HugePages_Free:     64
Node 0 HugePages_Surp:      0
Node 1 AnonHugePages:         0 kB
Node 1 ShmemHugePages:        0 kB
Node 1 HugePages_Total:    64
Node 1 HugePages_Free:     64
Node 1 HugePages_Surp:      0

So is there no huge page support in asmfish? Or is is there something wrong with my configuration?

**Comment by ChristophHeilmann** [comment]
Ok, I read in the Changelog that asmfish don't support Huge Pages. 

I never thought that Transparent Huge Pages could improve the performance, but i tried the setting transparent_hugepage=always and I got a speed increase of 12%!

I don't no if you can exceed this value with libhugetlbfs.

**Comment by hero2017** [comment]
Do you mean Large Pages, like in Windows? If so then yes it has support for that and yes you can expect up to 12% speed increase with it enabled.

**Comment by tthsqe12** [comment]
Unlike the windows version, the linux version does not display whether the large page allocation was successful or not. This is because I was never able to test it.

**Comment by ChristophHeilmann** [comment]
So meminfo is not enough for testing? Maybe the tool procps-ng / proceps can help see  https://serverfault.com/questions/527085/linux-non-transparent-per-process-hugepage-accounting and https://gitlab.com/procps-ng/procps
