### ISSUE TITLE
NUMA bug? starting from asmFisW_2017-08-05

### ISSUE THREAD

**Issue by Rechenschieber** [lantonov/asmFish#81]
It looks to me like there is a problem recognizing NUMA nodes:
[http://www.abdul-h.de/pictures/fishBug.jpg](url)
In version 2017-08-03 everything is still OK, but from version 2017-08-05 I get this strange output shown in the picture.

Best regards,
Lukas Cimiotti

Thank you for your great work :)

**Comment by tthsqe12** [comment]
So you have a 2 node machine with 22cores/node? If this is the case, this is probably a simple printing bug.
Other than the node numbers of 5075968, is the output expected?

**Comment by Rechenschieber** [comment]
Looks like performance is OK, but for 2 socket computers, NUMA isn't a big deal. I might check tomorrow using my 4 socket Xeon E5-4650 which suffers a lot if NUMA support isn't perfect.

**Comment by hero2017** [comment]
While you're there with the 4 socket E5-4650 and if it's not too much trouble, would you mind just posting the avg. kN/s you get at some position (you can post the FEN you tested) and for how long you left it running at that position (and the hash size you used)? Just trying to gauge how much faster I can expect it to be over my dual E5-2696v3.

**Comment by Rechenschieber** [comment]
@hero2017 
A dual E5-2696v3 is roughly 40% faster than that 4 socket computer. I've three 2x E5-2696v3 computers myself. I can be a bit more precise when I'm back from work. The 4x E5-4650 is nearly exactly as fast as a 2x E5-2696v2. And it's extremely slow with engines that have no NUMA support. So it is very good for checking NUMA capabilities. But it's a bad idea to buy one for chess.

**Comment by Rechenschieber** [comment]
On a 4 socket 4x E5-4650 it looks like this:
[http://www.abdul-h.de/pictures/fishBug1.jpg](url)
Performance is not affected, so this is a cosmetic problem.

**Comment by lantonov** [comment]
Fixed with 43ecbf820fe8601dec6b29b594f39824b1fdd44a

**Comment by Rechenschieber** [comment]
Thank you for fixing this. It now works very well :)
