### ISSUE TITLE
lets take a break for a while

### ISSUE THREAD

**Issue by tthsqe12** [lantonov/asmFish#83]
I have ported the x86 and arm versions to fasmg. There I am using the x86 macros created by the author of fasmz and my own macros for the implementation of the arm 64 bit architecture. With this approach, one program (fasmg) can assemble all of the version for windows/linux/osx/android. The only problem is that the ISA is implemented completely in macros, which fasmg then interprets. This causes the assemble time to go from instantaneous to:
 - windows: 22 seconds/executable
 - linux: 18 seconds/executable
 - osx: 18 seconds/executable
 - android: 13 seconds/executable

**Comment by Ipmanchess** [comment]
Congrats..great amazing work you did!!

Next after a deserved break..think maybe on a Cluster version ;)

Ipman.

**Comment by lantonov** [comment]
Absolutely deserved! Have a helpful and refreshing holiday!

**Comment by mausalimi** [comment]
amazing work. :)

**Comment by tthsqe12** [comment]
During the porting process, I found a weird bug in the gnu assembler which was causing it to generate incorrect machine code in two places. See if you can notice it in fixed depth testing!

**Comment by lantonov** [comment]
Which pairs of executables to test ?

**Comment by ghost** [comment]
Thank you - enjoy the break !!

**Comment by lantonov** [comment]
Good work !
