### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Alexei1981** [lantonov/asmFish#84]
Hello. When will the asmfish update?
Thanks.

**Comment by tthsqe12** [comment]
During the lull in stockfish progress, asmfish is undergoing major renovations on the back end. When these renovations are complete and when the stockfish team has gained some significant elo, asmfish is will be updated.

**Comment by lantonov** [comment]
The updated asmFish for fasmg assembler is in https://github.com/lantonov/asmFish/commits/fasmg
