### ISSUE TITLE
asmFish project on hold or abandoned

### ISSUE THREAD

**Issue by hero2017** [lantonov/asmFish#86]
I've been out of the scene for a while and I see the latest lantonov version is a month old now. Has asmFish been abandoned? I see some talk about fasmg.exe now and that tthsqe12 has what appears to be an updated version of asmFish:

x86	Good bishops on the main diagonals	a day ago (tthsqe12)

asmFish	some warning messages on linux	a month ago (lantonov)

So are we supposed to check tthsque12's github for the latest version of asmFish from now on? There's no changelog there so it's hard to understand what exactly has been added with each release.

Why the change from fasm to fasmg? Is there some benefit to this? From what I read about the difference is that it fasmg has better cpu architecture support but at the cost of performance so I'm confused as to why we needed this. I think with fasm we still had all the most common versions like popcnt, bmi2 or was this due to armFish? So we users who don't use or care about armFish for using on an android device are supposed to pay the price with a slower asmFish? Just trying to understand this.

Lastly, I see the make.bat file reference 'set include=x86\include' so are the compiled executables going to be 32bit versions of AsmFish only? I've compiled one and it doesn't appear to be 32 bit or I'd see *32 at the end of the process in Windows' task manager wouldn't I?

**Comment by lantonov** [comment]
Check issue #85. With fasmg we have the latest executables updated with SF patches for all major OS

**Comment by hero2017** [comment]
Thanks Lantonov. I saw that but I didn't see some of my questions answered there.

Why the change to fasmg now?

Also, in the "Building" description I see it says "However, fasmg is currently only available as an x86 executable." Just to be sure this doesn't mean the executables will be 32bit only right?

**Comment by lantonov** [comment]
No, asmFish executables are all 64-bit. We don't maintain 32-bit asmFish. The above sentence means that fasmg.exe itself is 32-bit. But it can make 64-bit compiles. BTW, it was the same with fasm.exe, though the assembler had also a 64-bit executable.
The change to fasmg.exe was done because it can make executables for all OS from the same source code (well, almost the same).

**Comment by hero2017** [comment]
Ok that's what I thought. Thank you sir.
