### ISSUE TITLE
Bench command gives 0 (zero) nodes for position 40 and 41, is that ok?

### ISSUE THREAD

**Issue by Saugstrahler** [lantonov/asmFish#89]
*** bench hash 1024 threads 6 depth 15 ***
info string hash set to 1024 MB page size 2048 KB
1:      nodes: 1543199          13419 knps
2:      nodes: 1253905          12926 knps
3:      nodes: 391426           19571 knps
4:      nodes: 1490826          14198 knps
5:      nodes: 885207           12467 knps
6:      nodes: 1173122          11615 knps
7:      nodes: 989018           12362 knps
8:      nodes: 2781236          13906 knps
9:      nodes: 2191684          12668 knps
10:     nodes: 552155           13803 knps
11:     nodes: 1277511          11613 knps
12:     nodes: 1214752          11043 knps
13:     nodes: 1710455          12860 knps
14:     nodes: 487434           11888 knps
15:     nodes: 894808           13981 knps
16:     nodes: 237772           16983 knps
17:     nodes: 291513           18219 knps
18:     nodes: 22362            22362 knps
19:     nodes: 477639           22744 knps
20:     nodes: 2009245          19698 knps
21:     nodes: 167577           20947 knps
22:     nodes: 149093           24848 knps
23:     nodes: 558508           29395 knps
24:     nodes: 495375           18347 knps
25:     nodes: 53704            17901 knps
26:     nodes: 125394           17913 knps
27:     nodes: 1622708          16903 knps
28:     nodes: 2211105          15462 knps
29:     nodes: 695841           17396 knps
30:     nodes: 168608           21076 knps
31:     nodes: 214701           23855 knps
32:     nodes: 171547           21443 knps
33:     nodes: 97578            24394 knps
34:     nodes: 706529           21409 knps
35:     nodes: 409102           20455 knps
36:     nodes: 140851           28170 knps
37:     nodes: 922638           18090 knps
38:     nodes: 20621            10310 knps
39:     nodes: 33603            11201 knps
40:     nodes: 0                0 knps
41:     nodes: 0                0 knps
42:     nodes: 969164           10768 knps
===========================
Total time (ms) : 2196
Nodes searched  : 31809516
Nodes/second    : 14485207

**Comment by ChessMan3** [comment]
Yes, thats ok - positions are stalemate  ( 8/8/8/8/8/6k1/6p1/6K1 w - - ) and mate ( 7k/7P/6K1/8/3B4/8/8/8 b - - )
