### ISSUE TITLE
No more 'base.exe' for newer versions?

### ISSUE THREAD

**Issue by rwbc** [lantonov/asmFish#91]
A pity.

**Comment by lantonov** [comment]
I will make some base versions for Linux, Windows and Mac. Thought no one uses them

**Comment by rwbc** [comment]
Everyone who still uses a 64 bit OS w/o popcount hardware needs them. Thanks a lot for considering!

**Comment by mausalimi** [comment]
honestly, building your own binary is an extremely easy task...

**Comment by MSoszynski** [comment]
Please continue the nopop/base compiles. I have a Linux system but need Windows compiles for certain GUIs. It is not "extremely easy" for me to cross-compile effectively.
