### ISSUE TITLE
FYI: asmFish as docker container

### ISSUE THREAD

**Issue by ksylvan** [lantonov/asmFish#94]
This is not an issue, just an FYI.

I created a docker automated build to build the latest asmfish:

https://hub.docker.com/r/kayvan/asmfish/

Anyone with Docker installed can now run asmfish like this:

```
docker run --rm -i kayvan/asmfish:2017-11-20
```

The `2017-11-20` is the tag (see https://hub.docker.com/r/kayvan/asmfish/tags/ ) and will be updated as the source is updated, or if you just want to run the latest, you can omit that:

```
docker run --rm -i kayvan/asmfish
```

Works great. Thanks for making asmfish available and maintaining it!

**Comment by lantonov** [comment]
Thanks for adapting asmFish for docker. Can you explain with a few sentences what this is used for in this framework because I, and I suppose most people haven't heard about docker?

**Comment by ksylvan** [comment]
Docker provides a way to run applications securely isolated in a container, packaged with all its dependencies and libraries. The promise of docker is that your image is built once, pushed to the docker hub, and can just be pulled and run anywhere that Docker can run. That means MacOS, Windows, Linux machines, all run the same image.

In this particular context, this means that we don't have to compile `asmfish` locally or install a binary on the local machine, you can just run the (quite small) container:

```
$ docker image ls
REPOSITORY            TAG                   IMAGE ID            CREATED             SIZE
kayvan/asmfish        2017-11-20            248dd3c0dfd9        10 days ago         65.8MB
kayvan/stockfish      181117                ee7f775d5645        11 days ago         208MB
kayvan/stockfish      latest                ab0083a5d6fd        2 weeks ago         208MB
kayvan/stockfish      151117                ebbc93dce1ff        2 weeks ago         208MB
```

It also means that you can run multiple versions of `asmfish` or `stockfish` (for example, to run a local computer-vs-computer tournament) by simply pulling and running different tagged versions.

The `docker run` documentation is here: https://docs.docker.com/engine/reference/commandline/run/

Full docs at https://docs.docker.com

**Comment by ksylvan** [comment]
```
$ docker run --rm -it kayvan/asmfish:2017-11-20 bench
asmFishL_2017-11-20_popcnt
warning: sys_mbind failed rax: ffffffffffffffff
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 222124           1898 knps       117 ms
2:      nodes: 229944           2189 knps       105 ms
3:      nodes: 90840            3785 knps       24 ms
4:      nodes: 155373           2466 knps       63 ms
5:      nodes: 95586            2222 knps       43 ms
6:      nodes: 164936           2228 knps       74 ms
7:      nodes: 160359           2109 knps       76 ms
8:      nodes: 447070           2390 knps       187 ms
9:      nodes: 209941           2078 knps       101 ms
10:     nodes: 136184           2476 knps       55 ms
11:     nodes: 208624           2196 knps       95 ms
12:     nodes: 166800           2166 knps       77 ms
13:     nodes: 221196           2378 knps       93 ms
14:     nodes: 87949            2145 knps       41 ms
15:     nodes: 98652            2294 knps       43 ms
16:     nodes: 99763            2625 knps       38 ms
17:     nodes: 68444            3111 knps       22 ms
18:     nodes: 15333            3833 knps       4 ms
19:     nodes: 46242            3853 knps       12 ms
20:     nodes: 274374           3610 knps       76 ms
21:     nodes: 37996            4221 knps       9 ms
22:     nodes: 28567            4761 knps       6 ms
23:     nodes: 84517            4448 knps       19 ms
24:     nodes: 41672            3205 knps       13 ms
25:     nodes: 9407             3135 knps       3 ms
26:     nodes: 40112            3085 knps       13 ms
27:     nodes: 215193           2988 knps       72 ms
28:     nodes: 228546           2657 knps       86 ms
29:     nodes: 100224           2784 knps       36 ms
30:     nodes: 30002            3750 knps       8 ms
31:     nodes: 60540            4324 knps       14 ms
32:     nodes: 59407            4569 knps       13 ms
33:     nodes: 27036            4506 knps       6 ms
34:     nodes: 75449            3772 knps       20 ms
35:     nodes: 143794           3784 knps       38 ms
36:     nodes: 73542            4596 knps       16 ms
37:     nodes: 385258           3350 knps       115 ms
38:     nodes: 5572             2786 knps       2 ms
39:     nodes: 19371            2421 knps       8 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          0 ms
42:     nodes: 149834           2052 knps       73 ms
===========================
Total time (ms) : 1916
Nodes searched  : 5015773
Nodes/second    : 2617835
```

**Comment by lantonov** [comment]
Thanks for explaining. I will look in the documentation to see if this can be used for live / semi-live tournaments over the web.
I am a little worried about the warning  `sys_mbind failed rax: ffffffffffffffff`. It doesn't seem to influence speed or bench though it's unclear if it may affect other parameters. In any case, it would be better to make so that sys_mbind works normally in docker. It may require a change in the asmFish code. On the other hand, this may just indicate that the image is detached from the system (which is true in case of docker) and sys_mbind is superfluous in this case.

**Comment by ksylvan** [comment]
What does that `sys_mbind` call do?

**Comment by ksylvan** [comment]
Looks like adding `--privileged` to the invocation fixes that:

```
$ docker run --privileged -it --rm kayvan/asmfish:2017-11-20 bench
asmFishL_2017-11-20_popcnt
*** bench hash 16 threads 1 depth 13 ***
1:      nodes: 222124           2115 knps       105 ms
2:      nodes: 229944           2299 knps       100 ms
3:      nodes: 90840            3364 knps       27 ms
4:      nodes: 155373           2390 knps       65 ms
5:      nodes: 95586            2172 knps       44 ms
6:      nodes: 164936           2170 knps       76 ms
7:      nodes: 160359           2004 knps       80 ms
8:      nodes: 447070           2340 knps       191 ms
9:      nodes: 209941           2120 knps       99 ms
10:     nodes: 136184           2308 knps       59 ms
11:     nodes: 208624           2128 knps       98 ms
12:     nodes: 166800           2166 knps       77 ms
13:     nodes: 221196           2328 knps       95 ms
14:     nodes: 87949            2045 knps       43 ms
15:     nodes: 98652            2406 knps       41 ms
16:     nodes: 99763            2494 knps       40 ms
17:     nodes: 68444            2975 knps       23 ms
18:     nodes: 15333            3066 knps       5 ms
19:     nodes: 46242            3853 knps       12 ms
20:     nodes: 274374           3266 knps       84 ms
21:     nodes: 37996            3799 knps       10 ms
22:     nodes: 28567            4761 knps       6 ms
23:     nodes: 84517            4971 knps       17 ms
24:     nodes: 41672            2976 knps       14 ms
25:     nodes: 9407             2351 knps       4 ms
26:     nodes: 40112            3085 knps       13 ms
27:     nodes: 215193           2908 knps       74 ms
28:     nodes: 228546           2657 knps       86 ms
29:     nodes: 100224           2505 knps       40 ms
30:     nodes: 30002            3000 knps       10 ms
31:     nodes: 60540            3783 knps       16 ms
32:     nodes: 59407            3960 knps       15 ms
33:     nodes: 27036            4506 knps       6 ms
34:     nodes: 75449            3429 knps       22 ms
35:     nodes: 143794           3423 knps       42 ms
36:     nodes: 73542            4596 knps       16 ms
37:     nodes: 385258           3210 knps       120 ms
38:     nodes: 5572             2786 knps       2 ms
39:     nodes: 19371            2421 knps       8 ms
40:     nodes: 0                0 knps          0 ms
41:     nodes: 0                0 knps          0 ms
42:     nodes: 149834           1872 knps       80 ms
===========================
Total time (ms) : 1965
Nodes searched  : 5015773
Nodes/second    : 2552556
```

**Comment by lantonov** [comment]
`sys_mbind` sets the NUMA memory policy for a given memory range and defines from which node the memory is allocated. Seems that the `--privileged` option overrides the sys_mbind allocation. The speed decreases a bit with option `--privileged` but this might not be statististically significant.
In NUMA, each thread is bound with `sys_mbind` to a specific node and this is called "node affinity". By creating a memory image, I suppose that the node affinity is broken and therefore the warning. Maybe `--privileged` acts like the modes `MPOL_LOCAL` or `MPOL_PREFERRED` which select an explicit local allocation for the memory range.

**Comment by ksylvan** [comment]
In either case, `asmFish` seems to work well. I don't see the `sys_mbind` warning as being a big deal. I have run long extended tournaments with `stockfish` versus `asmfish` and it does well (`asmfish` draws most of the time, occasionally wins, rarely loses).

**Comment by lantonov** [comment]
I perused the documentation of docker. It is too extensive for me to learn and many of the terms are unusual to me. I am mainly interested if docker can be used in the following scenario:
1. asmFish plays on some server (or a computer connected to the web), either with another engine or alone analysing a position
2. moves and evaluations, and also the info that you see on the screen in command mode are output by the engine(s) either in server memory or in a file which can be accessed through an open port on the server and downloaded to another computer connected to the web
Is this scenario possible with docker?

**Comment by ksylvan** [comment]
Yes. It is certainly possible. The only thing that docker gets me is that I don't have to build `asmfish` (or stockfish, for that matter) and can run the same package on a variety of machines.

Other than that, it's not any different than the compiled binary. If we need to have `asmfish` have access to files on the host, we do that using the `-v` option.
