### ISSUE TITLE
Losing on time when having over 30s lead

### ISSUE THREAD

**Issue by pjdouillard** [lantonov/asmFish#95]
I see these from time to time and I want to know why asmFish 'eventually' struggles and finally lose the 
game on time while having a +30 sec lead on the clock with a +46 eval (for example).

The game is between these system:

white: asmFishW_2017-11-24_bmi2 (12 threads) : i7-8700k 6-core@5Ghz, 1024 MB hash
black: SF_clone_popcnt (40 threads): 2 x Xeon 10-core CPU @ 2.30GHz, 1024 MB hash

[Event "Rated game, 5 min"]
[Site "Engine Room"]
[Date "2017.11.30"]
[Round "?"]
[White "Cisco2015, asmFishW_2017-11-24"]
[Black "Someone, SF_clone"]
[Result "0-1"]
[ECO "C88"]
[WhiteElo "2482"]
[BlackElo "2495"]
[Annotator "0.22;0.11"]
[PlyCount "262"]
[EventDate "2017.11.30"]
[SourceTitle "playchess.com"]
[TimeControl "300"]

 1. e4 {0.01/0 0} e5 {B 0} 2.
Nf3 {0.22/19 0} Nc6 {B 0} 3. Bb5 {0.12/19 0} a6 {B 0} 4. Ba4 {0.01/0 0} Nf6 {
B 0} 5. O-O {0.23/20 0} Be7 {B 0} 6. Re1 {0.19/21 0} b5 {B 0} 7. Bb3 {0.40/21 0
} O-O {B 0} 8. a4 {0.18/21 0} b4 {B 0} 9. d4 {0.23/22 0} d6 {B 0} 10. dxe5 {
0.17/22 0} Nxe5 {B 0} 11. Nxe5 {0.08/22 0} dxe5 {B 0} 12. Qf3 {0.08/22 0} Bc5 {
0.11/28 10} 13. h3 {0.17/28 0} Be6 {0.11/28 6} 14. Nd2 {0.01/0 0} Qe7 {0.11/30
6} 15. Qg3 {0.07/31 0} Qd6 {0.11/29 0} 16. Nc4 {-0.08/22 0} Bxc4 {0.10/27 6}
17. Bxc4 {0.06/31 0} Rad8 {0.01/29 5} 18. Be3 {0.01/0 0} Bxe3 {0.30/28 13} 19.
Qxe3 {0.01/0 0} Qc6 {0.24/30 23} 20. b3 {0.48/33 0} Rd4 {0.21/33 6} 21. Red1 {
0.37/31 0} Rfd8 {0.61/30 14} 22. Rxd4 {0.55/34 0} Rxd4 {0.62/31 1} 23. Qg5 {
0.45/29 0} Qd6 {0.45/32 7} 24. Qf5 {0.67/35 5} a5 {0.79/30 2} 25. Qc8+ {
0.72/32 2} Qd8 {0.66/33 6} 26. Qa6 {0.62/35 7} c5 {0.63/34 0} 27. Qa7 {0.46/36
8} Nxe4 {0.62/34 1} 28. Qxf7+ {0.65/36 14} Kh8 {0.59/35 0} 29. Re1 {0.68/36 10}
Nd6 {0.46/39 0} 30. Qh5 {0.46/38 11} Nxc4 {0.46/42 0} 31. bxc4 {0.46/38 14} e4
{0.46/45 0} 32. Qxc5 {0.46/41 4} h6 {0.46/46 2} 33. Qc6 {0.46/42 3} Qf6 {
0.46/42 12} 34. Qa8+ {0.46/44 0} Qd8 {0.46/41 4} 35. Qxd8+ {0.46/45 14} Rxd8 {
0.46/52 0} 36. Rxe4 {0.46/49 5} Rd2 {0.46/51 1} 37. Re5 {0.46/51 5} Rxc2 {
0.46/55 0} 38. Rxa5 {0.46/55 4} b3 {0.46/55 3} 39. Rb5 {0.46/55 1} b2 {0.46/54
0} 40. Kh2 {0.46/56 4} Rxc4 {0.46/56 9} 41. Rxb2 {0.46/60 0} Rxa4 {0.46/55 0}
42. Kg3 {0.46/50 6} h5 {0.46/46 7} 43. h4 {0.46/59 4} g6 {0.46/59 0} 44. f3 {
0.46/67 4} Kh7 {0.46/60 4} 45. Rb6 {0.46/71 4} Kg7 {0.46/70 6} 46. Rb2 {
0.46/76 0} Kf6 {0.46/59 7} 47. Rb1 {0.46/72 4} Ke6 {0.46/65 3} 48. Rb6+ {
0.46/73 4} Kf7 {0.46/60 4} 49. Rb7+ {0.46/75 4} Ke6 {0.46/74 10} 50. Rb6+ {
0.46/73 4} Kf7 {0.46/65 3} 51. Rd6 {0.46/77 4} Kg7 {0.46/63 3} 52. Kh3 {
0.46/79 4} Kh7 {0.46/63 3} 53. Rd8 {0.46/77 4} Kg7 {0.46/66 4} 54. Kg3 {
0.46/75 7} Kf6 {0.46/65 3} 55. Rd1 {0.46/74 3} Ke7 {0.46/63 3} 56. Rg1 {
0.46/76 4} Ra3 {0.46/61 2} 57. Rb1 {0.46/71 3} Kf6 {0.46/66 4} 58. Rd1 {
0.46/73 3} Ra2 {0.46/60 2} 59. Rd6+ {0.46/74 4} Kf7 {0.46/67 2} 60. Rd1 {
0.46/71 3} Kg7 {0.46/58 3} 61. Rh1 {0.46/70 25} Ra3 {0.46/64 2} 62. Kf4 {
0.46/61 3} Kh6 {0.46/56 3} 63. Rc1 {0.46/65 6} Ra5 {0.46/56 2} 64. Rc7 {
0.46/65 18} Ra6 {0.46/65 3} 65. Rd7 {0.46/61 8} Ra3 {0.46/62 3} 66. Rd5 {
0.46/57 13} Ra7 {0.46/67 0} 67. Rd8 {0.46/57 1} Rf7+ {0.46/54 2} 68. Kg3 {
0.46/57 1} Ra7 {0.46/68 2} 69. Rb8 {0.46/52 4} Ra4 {0.46/67 2} 70. Rb6 {
0.46/50 2} Kh7 {0.46/67 2} 71. Rd6 {0.46/50 2} Kh6 {0.46/59 12} 72. Rc6 {
0.46/44 3} Kh7 {0.46/61 1} 73. Rc3 {0.46/43 3} Kg7 {0.46/53 4} 74. Rc2 {
0.46/40 2} Kf7 {0.46/61 1} 75. Rb2 {0.46/39 6} Kg7 {0.46/61 1} 76. Rb5 {
0.46/37 2} Kf6 {0.46/66 1} 77. Rb2 {0.46/35 1} Rd4 {0.46/58 1} 78. Rb6+ {
0.46/32 4} Kf7 {0.46/64 1} 79. Rb2 {0.46/32 1} Kf8 {0.46/60 2} 80. Kh3 {
0.46/32 3} Kg7 {0.46/55 1} 81. Re2 {0.46/28 1} Ra4 {0.46/57 1} 82. Re4 {
0.45/27 2} Ra2 {0.46/57 1} 83. Rc4 {0.45/24 1} Rd2 {0.46/59 1} 84. Rc6 {
0.38/27 0} Rd1 {0.46/54 2} 85. Ra6 {0.38/28 1} Rd5 {0.46/53 1} 86. Ra8 {
0.38/30 0} Rd1 {0.46/56 1} 87. Ra7+ {0.46/36 0} Kf6 {0.46/49 0} 88. Ra6+ {
0.38/44 0} Kf7 {0.46/54 1} 89. Ra7+ {0.38/44 0} Kf6 {0.46/53 0} 90. Ra6+ {
0.38/47 0} Kf7 {0.46/48 6} 91. Ra2 {0.38/37 0} Rh1+ {0.16/36 2} 92. Kg3 {
0.65/1 0} Rb1 {0.16/44 0} 93. Ra3 {0.23/46 0} Rb5 {0.16/43 1} 94. f4 {0.23/38 0
} Kf6 {0.16/53 0} 95. Kf3 {0.23/44 0} Kf5 {0.16/50 1} 96. Re3 {0.23/49 0} Kf6 {
0.16/45 1} 97. g3 {0.23/49 0} Rb4 {0.16/52 0} 98. Rd3 {0.23/56 0} Rb5 {0.16/45
3} 99. Rd6+ {0.23/47 0} Kg7 {0.16/56 1} 100. Rd3 {0.23/44 0} Kf6 {0.16/54 1}
101. Re3 {0.23/57 0} Rb1 {0.16/51 1} 102. Ke4 {0.23/58 0} Kg7 {0.16/48 0} 103.
Rd3 {0.23/47 0} Rb5 {0.16/49 0} 104. Ke3 {0.23/43 0} Rb4 {0.16/55 0} 105. Kf3 {
0.23/57 0} Rb6 {0.16/53 0} 106. Kg2 {0.23/43 0} Kf6 {0.16/56 0} 107. Ra3 {
0.23/59 0} Rb1 {0.16/54 0} 108. Kf3 {0.23/44 0} Kf7 {0.16/52 0} 109. Ra2 {
0.23/38 0} Rb3+ {0.16/56 0} 110. Kg2 {0.23/59 0} Kf6 {0.16/58 0} 111. Ra8 {
0.23/42 0} Rb1 {0.16/47 0} 112. Kf3 {0.23/39 0} Rb3+ {0.16/52 0} 113. Kg2 {
0.23/62 0} Rb4 {0.16/54 0} 114. Rf8+ {0.23/41 0} Kg7 {0.16/58 0} 115. Ra8 {
0.23/46 0} Rd4 {0.16/50 0} 116. Ra5 {0.23/36 0} Rd6 {0.16/48 0} 117. Kf2 {
0.40/3 0} Rb6 {0.16/49 0} 118. Kg2 {0.25/3 0} Kf6 {0.16/54 0} 119. Kh3 {
0.23/60 0} Rb3 {0.16/55 2} 120. Ra7 {0.23/59 0} Rc3 {0.16/47 0} 121. Ra1 {
0.23/1 0} Kf7 {0.16/45 0} 122. Kh2 {0.23/3 0} Kg7 {0.16/48 0} 123. Re1 {
0.23/3 0} Kf6 {0.16/49 0} 124. Kh3 {0.23/3 0} Kf7 {0.16/51 0} 125. Kh2 {
0.23/3 0} Rb3 {0.16/42 0} 126. Ra1 {0.23/1 0} Rb2+ {0.16/40 1} 127. Kh3 {
0.23/5 0} Rb3 {0.16/43 0} 128. Kh2 {0.23/40 0} Ke6 {0.16/40 1} 129. Ra6+ {
0.16/3 0} Kf5 {0.11/34 0} 130. Kg2 {0.00/43 0} Rb2+ {0.11/43 0} 131. Kf1 {
0.00/48 0 . Time (Lag: Av=0.32s, max=0.9s)} Rb1+ {0.11/42 0} 0-1

Other question: For a 5 min game, should I reduce my hash size?

Thx!

**Comment by lantonov** [comment]
Did you use USE_SPAMFILTER = 1 as in #90 ?
Reducing hash size might help as it reduces search depth and, respectively, the amount of spamming.

**Comment by pjdouillard** [comment]
No I haven't use this USE_SPAMFILTER option yet since my main problem with EGT was that they were never set properly (only the engine used it, but not the GUI - never thought that the GUI needed it too).

How do I use that parameter on the compile line?

"fasmg.exe" "x86\fish.asm" "asmFishW_%datestamp%_bmi2.exe" -e 1000 -i "VERSION_OS='W'" -i "PEDANTIC = 1" -i "VERSION_POST = 'bmi2'" **-i "USE_SPAMFILTER = 1"**   ???

It seems to compile, so I will test it and come back.

Thank you for your help!

**Comment by lantonov** [comment]
This is correct

**Comment by pjdouillard** [comment]
Haven't seen the issue rise again since USE_SPAMFILTER = 1 in short time control games.  Thank you for reminding me this option that I forgot to test.

**Comment by lantonov** [comment]
You are welcome!
