### ISSUE TITLE
Dynamic Contempt

### ISSUE THREAD

**Issue by jjoshua2** [lantonov/asmFish#96]
Could we get the new dynamic contempt ported to asmfish? I think it would really help with the speed of asmfish on a fast computer to be able to beat all the lesser chess entities :)

**Comment by hero2017** [comment]
Yes I like this idea as well.

But I'm not sure what's happening with asmFish. There's been no updates for like 2 months...probably the longest I've ever seen.

**Comment by lantonov** [comment]
The truth is that some of the new patches are too difficult for me and I need the help of Mohammed Li who is the asm expert

**Comment by hero2017** [comment]
I see. Is tthsque12 not available to help any more? Is he on a long vacation?

**Comment by lantonov** [comment]
I hope it's a vacation. He left the project last year right at this time.

**Comment by hero2017** [comment]
tthsqe12's last github update was only a month ago. But it sounds like you don't know either way so I think we're only left to assume that asmFish is finished unless we hear back from tthsqe12 and see it updated again, or offering to help. And that's a real shame because it's still the fastest chess engine however it's a bit behind in elo now due to the missing updates.

**Comment by lantonov** [comment]
Agreed. This project should get more attention from assembly programmers. Last year, I tried to preserve the project from a zip file on my disk as the tthsqe12 site was closed. By a happy circumstance, a person with a knowledge in assembly helped in updating to the latest SF patches (about 15 patches). Then tthsqe12 became interested again and started not only updating to the latest patches but also other improvements and additions like armFish, mateFish, etc. Most of it was by user requests and some, like armFish required a lot of programming and writing anew. I am afraid that this may have been a repulsive chore for Moha who got disillusioned by this project.

**Comment by mausalimi** [comment]
but why would he have spent that much time to port the whole thing to fasmg and leave the project right after finishing? strange...

**Comment by hero2017** [comment]
Maybe he's incarcerated :-)

**Comment by lantonov** [comment]
God forbid!

**Comment by jjoshua2** [comment]
Looking at the dynamic contempt patch, it doesn't look that difficult? https://github.com/mcostalba/Stockfish/commit/be382bb0cf5927dc10ff9be882f6980a78d1484a
It looks like mostly you just need to change a few things to VALUE_DRAW and use a contempt / 2.

I think this would help a ton because on a fast computer asmfish is so fast it needs contempt to punish those. I've been trying Brainfish and the contempt works really well now.

**Comment by lantonov** [comment]
I can try this. Good it's non-functional so doesn't change bench

**Comment by 0zymandia2** [comment]
> but why would he have spent that much time to port the whole thing to fasmg and leave the project right after finishing? strange...

Strange? Not at all. He reached a goal and is now getting his beauty sleep.

> tthsqe12 became interested again and started not only updating to the latest patches but also other improvements and additions like armFish, mateFish, etc. Most of it was by user requests and some, like armFish required a lot of programming and writing anew. I am afraid that this may have been a repulsive chore for Moha who got disillusioned by this project.

I wouldn't expect him to take on any task he didn't feel like doing. He isn't known as TypingALot for nothing.

**Comment by jjoshua2** [comment]
I saw there is a many commits recently, but none seem to reference contempt? Was it done or not? How far behind are you still?

**Comment by lantonov** [comment]
asmFish has the patches up to the one implementing contempt (Dec 11). The new contempt is not done yet
